### ISSUE TITLE
Proposal: Log spam suppression

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#102]
This is a proposed mechanism to avoid the console being swamped by spammy log messages (for example if one starts printing every frame). The idea is that a log message be suppressed if it uses a format string used more than (approximately) Q times in the last T milliseconds.

Log filtering is done at the module level (i.e. one each for engine, cgame, sgame). A buffer contains records of the N (say 50) most recent unique format strings used for log messages. Besides the format string, the record contains an initial time (for the T ms period), a most recently seen time, number of times seen, and whether the message has been disabled. When a log message is received, the record for it is updated if it exists; otherwise the least recently seen message is removed. When updating a record, if T milliseconds have passed since the initial time, the initial time and count are reset. If the count reaches Q, then the message is disabled, and remains disabled until it drops out of the cache. A message like "Suppressing further messages of this type" is printed.

Naturally, there will be a cvar to disable log suppression (if you really want to see that debug message printed every frame). Log suppression should not used for messages printed by commands as they often print lengthy lists, and are usually triggered by the user's request. For messages that are known to legitimately print a lot of times, such as the list of loaded paks, there can be an API to log while bypassing the filter.

**Comment by DolceTriade** [comment]
Hmm, I would prefer spammy logs police themselves. Maybe something similar to glog's LOG_EVERY_N (https://github.com/google/glog/blob/master/src/glog/logging.h.in#L176). I almost want to switch to glog, but that seems like a lot of work so :-/

**Comment by slipher** [comment]
Using glog would make it slightly easier to write individual rate-limited log statements, but it doesn't do anything to help with the thousands of log statements that already exist. It's infeasible to try to figure out an appropriate limit for all of them. And if we have a limit by default, it will be easier in the future for developers to write log warnings, since they will not have to worry about excessive log spam.

**Comment by DolceTriade** [comment]
Fair enough. Another option would be to allow call site specific filtering. This would require us to make our log functions macros though, but I think it is possible to do this in a way that doesn't require us to rewrite every log statement.

**Comment by slipher** [comment]
I'm going to commit the stuff not directly involving log filtering so the PR does not accumulate too much cruft.

**Comment by slipher** [comment]
Implemented in #115.
