### ISSUE TITLE
Portals don't render the skybox

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1021]
Portals don't render the skybox, while it is well known, it looks like we haven't reported it yet with a dedicated ticket.

![unvanquished_2024-01-08_003558_000](https://github.com/DaemonEngine/Daemon/assets/2311649/e4cbb936-014d-41d5-846a-1ac0e73b85b6)

**Comment by VReaperV** [comment]
Fixed by #1044.
