### ISSUE TITLE
"Static light" (BSP entity dynamic light) feature

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#1051]
There is a feature for the renderer to add dynamic lights based on BSP entities with the `light` class name. There are no Tremulous or Unvanquished maps that use it. I don't know if this is a Wolfenstein thing, a half-assed Xreal demo or what. The lights only appear when using the tiled renderer, not the legacy dynamic light renderer (probably a regression). This is the only BSP entity other than `worldspawn` which is processed by the renderer.

I suppose this feature might be used for lights that change brightness since there is the possibility to add a custom shader which could be time-dependent. The possibilities of doing stuff with lights at runtime are limited though, since the BSP entities are not instantiated as real entities in the sgame, so you can't make them move around, enable/disable them, or anything like that. If we want to do dynamic light stuff in maps, it seems better to nuke these renderer light entities and define a proper networked entity.

There are a few [maps with `light` entities](https://users.unvanquished.net/~slipher/map-entity-directory.txt), but it appears all of these are just ones where the mapper used the `-keeplights` q3map2 flag for no good reason. The lights have no effect in-game because they are normally only added by the engine if they have the `noradiosity` key (which tells q3map2 *not* to process them). None of our known maps have that.

On Daemon master, you can force the light entities to be rendered on such a map (e.g. `stahl`) by setting the cvars `r_lightMode 1` and (to make the lights easier to see) `r_lightScale 500`.

![unvanquished_2024-02-21_001756_000](https://github.com/DaemonEngine/Daemon/assets/7809431/36eade29-58f5-4613-aa79-7348c8cd9da3)

Perhaps the feature has/had some use as a tool to quickly test lighting without the cost of full map compilation? No doubt the results are way different though.

`r_staticLight`, a cvar which enables/disables these entity-based lights, should get a more appropriate name like `r_lightEntities`.

**Comment by illwieckz** [comment]
This was probably a DOOM3 feature implemented in XreaL (like many other things including some material syntax). For having dealt a bit with the DOOM3-related renderer in NetRadiant and with DarkRadiant game configuration (that describes what is the light entity names) those light entities ring a bell.

**Comment by illwieckz** [comment]
This branch makes it possible to render those static lights with every light mode:

- https://github.com/DaemonEngine/Daemon/pull/1345

I believe I now grasp the feature investigating the stahl map and reading those comments helped:

```
bool     isStatic; // loaded from the BSP entities lump
bool     noRadiosity; // this is a pure realtime light that was not considered by XMap2
```

So, XreaL allowed to place light entities in maps that would not be baked by the `xmap2` map compiler (which was a fork of `q3map2`) if they had the `noRadiosity` property. It means the mapper could decide if a light entity was to be baked ad map compile time or rendered at render time by flipping that property on and off.

The q3map2 map compiler doesn't parse `noRadiosity` so the related lights in stahl are both baked by q3map2 and rendered by the engine (when the feature is properly enabled). It's possible to add `noRadiosity` support in q3map2 if needed.

Actually, we have a proof that we can render some BSP light entities in game without hacking some particles.

By considering all light entities `noRadiosity` and using a map compiled with `keepLights`, we may be able to render a map without baking it with q3map2 first (à la Doom3).
