### ISSUE TITLE
Some weird lines with CRN files

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1056]
Reported on IRC today by @sweet235.

JPEG:

![oIk](https://github.com/DaemonEngine/Daemon/assets/2311649/ec40952a-dea8-4dc9-a9fc-63c3448df338)

CRN:

![Iju](https://github.com/DaemonEngine/Daemon/assets/2311649/b9f1ab41-1e00-42a9-9051-7296beb5623f)

I noticed it with other textures in the past, on my end the glitch changes with the distance.

The bug is there since years. I suspect a bug in the mipmapping code.

The mipmap images are already part of the CRN file. When I convert CRN to DDS with crunch (that I assume to only change the container, not recompress the file), and load the DDS in GIMP, I see no issue in the precomputed mip-map images. So I assume this is a bug in our renderer.

**Comment by VReaperV** [comment]
Forcing a specific mipmap level (no interpolation) might help identify the issue.

**Comment by slipher** [comment]
Using Forlorn's floor texture as my testbed, I tried the 0.52.1 engine with recent assets and the bug was there. But 0.52.1 engine with 0.52.1 assets does not have the bug. So this suggests the possibility of an asset pipeline bug.

It does seem to be specific to certain mip levels. Setting various values of `r_picmip` or `r_imageMaxDimension` resulted in either the lines going away, or becoming bigger (due to lower resolution).

**Comment by sweet235** [comment]
> So this suggests the possibility of an asset pipeline bug.

This seems to be the case. I see similar lines with for `textures/shared_ex_src/light2`. When I convert the corresponding 5 png images to crn using crunch commit 4c4a009, the lines disappear.

**Comment by slipher** [comment]
I discovered a cvar `r_exportTextures` which causes the engine to dump all images it loads, including all mip levels, as KTX files. I tested with a 256x256 floor texture which looks the same as the one from OP screenshot (but the map was Forlorn). When opened in a KTX viewer program, the 128x128 mip level shows several black lines, and the 32x32 level shows one. 

![image](https://github.com/user-attachments/assets/fc1974ec-e2eb-469d-866b-cf66966bcee0)

**Comment by VReaperV** [comment]
So every 16 texels it seems like.

**Comment by VReaperV** [comment]
From dev channel:
> simply re-converting form png to crn fixes this
So I suppose we can close this as not-an-engine-bug.

**Comment by illwieckz** [comment]
Yes, I have a full-asset rebuild on my end and I can't reproduce the bug anymore.

**Comment by slipher** [comment]
For future reference, the program that can view KTX mip levels was https://github.com/kopaka1822/ImageViewer. Note that it builds as a Visual Studio project.
