### ISSUE TITLE
Detect non-main thread attempting to use IPC

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#1061]
If we use threads in the gamelogic VMs, we should detect if a non-main thread attempts to use the IPC facility and terminate the program instead of allowing potentially mysterious corruption. It can be done in C++ [like this](https://stackoverflow.com/a/13288025).

The difficult part would be actually communicating any message about what the programmer has done wrong, since the only way to log an error message is using IPC :)

**Comment by DolceTriade** [comment]
This is a good idea.
