### ISSUE TITLE
Can LIGHTMAP and DIFFUSEMAP stages have a sorting > OPAQUE?

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1086]
We have this code in `Tess_StageIteratorDepthFill()` from `tr_shade.cpp`:

```c++
switch ( pStage->type )
{
	case stageType_t::ST_COLORMAP:
		if ( tess.surfaceShader->sort <= Util::ordinal(shaderSort_t::SS_OPAQUE) )
		{
			Render_depthFill( pStage );
		}
		break;

	case stageType_t::ST_LIGHTMAP:
	case stageType_t::ST_DIFFUSEMAP:
	case stageType_t::ST_COLLAPSE_COLORMAP:
	case stageType_t::ST_COLLAPSE_DIFFUSEMAP:
		Render_depthFill( pStage );
		break;

	default:
		break;
}
```

Am I right the LIGHTMAP and DIFFUSEMAP stages can't use a sorting greater than OPAQUE, meaning we can do this instead?

```c++
if ( tess.surfaceShader->sort <= Util::ordinal(shaderSort_t::SS_OPAQUE) )
{
	switch ( pStage->type )
	{
		case stageType_t::ST_COLORMAP:
		case stageType_t::ST_LIGHTMAP:
		case stageType_t::ST_DIFFUSEMAP:
		case stageType_t::ST_COLLAPSE_COLORMAP:
		case stageType_t::ST_COLLAPSE_DIFFUSEMAP:
			Render_depthFill( pStage );
			break;

		default:
			break;
	}
}
```

**Comment by VReaperV** [comment]
I'd check what the skybox cloud layers do... They might be ST_DIFFUSEMAP and SS_ENVIRONMENT_NOFOG, though don't I remember for sure.

**Comment by illwieckz** [comment]
I added a warning for when those DIFFUSEMAP variants happen with sort being > OPAQUE and never got the warning printed, including maps with clouds.

I guess the code assumes it's always < OPAQUE for non-GENERIC, the test is there because as GENERIC said it is used for other things than painting textures.

**Comment by VReaperV** [comment]
Actually, Tess_StageIteratorDepthFill() is never used. The only place it was referenced before was the old skybox code, but it was never called there either. Maybe it's an unfinished feature?

**Comment by illwieckz** [comment]
Oh lol, so we better nuke it then…
