### ISSUE TITLE
Why do we build engine and non-nexe game with `-fno-strict-aliasing`?

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1158]
In `DaemonFlags.cmake` we set `-fno-strict-aliasing` on non-NACL, non-MSVC builds:

https://github.com/DaemonEngine/Daemon/blob/7b5abf5ab45886a553bf2913a56baaeb8acd2906/cmake/DaemonFlags.cmake#L192

It means this flag is used when building released engine for all platforms, and used when building dll and exe games. But this flag is not used when building nexe game. 

This flag is there since the very beginning of the Unvanquished repository, commit `98b3a14` “Upload the codebase”:

```diff
+set( CMAKE_C_FLAGS_RELEASE "-DNDEBUG -O3 -ffast-math -fomit-frame-pointer -fno-strict-aliasing" CACHE STRING "" )
+set( CMAKE_C_FLAGS_RELWITHDEBINFO "-DNDEBUG -O3 -ffast-math -fomit-frame-pointer -fno-strict-aliasing -g" CACHE STRING "" )
```

It has probably been carried over for all those years accross all rewrites.

But when doing some refactoring on `DaemonFlags.cmake` I thought that after 12 years I may carry it over like other people did before me, or question it.

What do you think about this flag?

**Comment by illwieckz** [comment]
Some type-punning issue:

So now we know:

```
engine/qcommon/msg.cpp: In function ‘void MSG_WriteDeltaFloat(msg_t*, float, float)’:
engine/qcommon/msg.cpp:626:24: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  626 |  MSG_WriteBits( msg, * ( int * ) &newV, 32 );
      |                        ^~~~~~~~~~~~~~~
engine/qcommon/msg.cpp: In function ‘float MSG_ReadDeltaFloat(msg_t*, float)’:
engine/qcommon/msg.cpp:635:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  635 |   * ( int * ) &newV = MSG_ReadBits( msg, 32 );
      |     ^~~~~~~~~~~~~~~
```

**Comment by illwieckz** [comment]
We also have this:

```
engine/renderer/tr_bsp.cpp: In function ‘unsigned int VertexCoordGenerateHash(const vec_t*)’:
engine/renderer/tr_bsp.cpp:6315:17: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 6315 |  hash += ~( * ( ( unsigned int * ) &xyz_epsilonspace[ 0 ] ) << 15 );
      |               ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
engine/renderer/tr_bsp.cpp:6316:16: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 6316 |  hash ^= ( * ( ( unsigned int * ) &xyz_epsilonspace[ 0 ] ) >> 10 );
      |              ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
engine/renderer/tr_bsp.cpp:6317:16: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 6317 |  hash += ( * ( ( unsigned int * ) &xyz_epsilonspace[ 1 ] ) << 3 );
      |              ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
engine/renderer/tr_bsp.cpp:6318:16: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 6318 |  hash ^= ( * ( ( unsigned int * ) &xyz_epsilonspace[ 1 ] ) >> 6 );
      |              ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
engine/renderer/tr_bsp.cpp:6319:17: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 6319 |  hash += ~( * ( ( unsigned int * ) &xyz_epsilonspace[ 2 ] ) << 11 );
      |               ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
engine/renderer/tr_bsp.cpp:6320:16: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 6320 |  hash ^= ( * ( ( unsigned int * ) &xyz_epsilonspace[ 2 ] ) >> 16 );
      |              ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by illwieckz** [comment]
It looks like only those 3 functions need the strict aliasing optimization to be disabled:

- `MSG_WriteDeltaFloat`
- `MSG_WriteDeltaFloat`
- `VertexCoordGenerateHash`

We can only disable this optimization when building those three functions, and use the optimization on everything else.

**Comment by DolceTriade** [comment]
Does it even give a measurable performance gain? Selectively disabling optimizations without any measurable gain more likely to cause confusion than anything else

**Comment by slipher** [comment]
I'm sure we have at least dozens of places where we access stuff through pointers of the wrong type. For example when interfacing with OpenGL or Recast libraries, we often have to cast between array of vec3_t and array of float. The warnings are just places where GCC can *prove* that violations happen. In other cases the compiler may not be able to prove a violation, but it may generate code that does not do what we want based on the *assumption* that violations do not happen.

**Comment by illwieckz** [comment]
> Selectively disabling optimizations without any measurable gain more likely to cause confusion than anything else

Well, previously we were disabling it for the whole engine build.

**Comment by illwieckz** [comment]
> I'm sure we have at least dozens of places where we access stuff through pointers of the wrong type. 

If we don't trust our pointers, then we may look to do the alternative thing: always use `-fno-strict-aliasing`, even with nexe.

I started that thread because I was surprised we don't use the same build flags given the way we build things.

**Comment by slipher** [comment]
> If we don't trust our pointers, then we may look to do the alternative thing: always use `-fno-strict-aliasing`, even with nexe.

Yes, that's a good idea. Having used exactly one compiler version for 9 years, it's not surprising that any bugs have stayed under the rug for now.

**Comment by illwieckz** [comment]
See #1160 for the alternative:

- https://github.com/DaemonEngine/Daemon/pull/1160

**Comment by slipher** [comment]
At the top of Crunch's crnlib.h is written the following:

```
// Important: If compiling with gcc, be sure strict aliasing is disabled: -fno-strict-aliasing
```

**Comment by illwieckz** [comment]
I wonder if there is a `#pragma` to disable strict aliasing on a per-file basis, it would be useful in such header.
