### ISSUE TITLE
What is `vboData_t.stpq`? It's only read, never set

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1183]
```
tr_local.h
735:		union { f16vec2_t *st; f16vec4_t *stpq; vec2_t *stf; };

tr_vbo.cpp
397:				Vector4Copy( inData.stpq[ v ], ptr[ v ].texCoords );
```

**Comment by VReaperV** [comment]
Isn't that texture coords + lightmap coordinates? They're set as either `st` or `stf` since it's a union.

**Comment by illwieckz** [comment]
The problem is the `pq` in `stpq`, we either set `st` as half float or `stf` float 2-components vectors, but we never set a 4-components half float vector.

**Comment by VReaperV** [comment]
Well, setting 2x 32fp should put data in all bits of the 4x 16fp. I don't know if it sets the correct data that way though, since it would just be splitting the mantissa and the exponent.

**Comment by illwieckz** [comment]
It looks like there is a single use case for 2 floats, and there is already a vec2_t copy code for that use case, and it's not that.

**Comment by slipher** [comment]
Removed in #1189.
