### ISSUE TITLE
White floor in map Tremor

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#1185]
On master much of the floor and other textures in `map-tremor_1.2.1.dpk` is replaced with all white. I have a build from April 12th that doesn't have this problem.

![unvanquished_2024-06-10_214738_000](https://github.com/DaemonEngine/Daemon/assets/7809431/dd57a16b-7c46-477f-b9f3-0589c81966a5)

**Comment by illwieckz** [comment]
Curious, that doesn't seem to affect `1.2.3`.

**Comment by slipher** [comment]
Never mind it was a bad `r_lightmode` setting saved. Don't know how that happened as I would never archive it on purpose.

**Comment by illwieckz** [comment]
Well, no `r_lightMode` value should produce that…

**Comment by illwieckz** [comment]
I reproduce with any `r_lightMode` value smaller than `3`, I consider this a bug.

**Comment by illwieckz** [comment]
Meh, breaking commit is 5328a3ffd36429df3b50cb5a619763bf6d5cbcf6…

I may have messed with some light style shader.

**Comment by illwieckz** [comment]
Actually what is painted is the light, but without the texture blended in.
