### ISSUE TITLE
Cross-compilation is broken

### ISSUE THREAD

**Issue by maek** [DaemonEngine/Daemon#122]
Hi guys,

I might have found a bug in the new `include-bin` generator process for glsl when cross-compiling:
basically, since the tool is cross-compiled you cannot run it on the host during the build process and that makes CMake complaining about missing binary and it doesn't generate the glsl include files.

From a quick search on the internet it seems there is not an easy solutinon to this (they suggest a 2-pass build).

**Comment by maek** [comment]
Some comments about this after I reported it on your channel:

> 11:16:00 | <+perturbed-83258> | Port to python? Or just do the cmake invocation (that has to be done for nacl also)
> 11:21:15 | <+Ingar> | should be a build dependecy provided by the host
> 11:22:04 | <+Ingar> | that's what you get for wanting to jam all dependencies in your src tree
> 11:22:51 | <+Ingar> | and that's what you get for cross-compiling :D

**Comment by slipher** [comment]
Instead of doing the hex dump thing, we might consider C++11 raw strings, as we only include things that resemble C source code. That would be easy enough that it could be done in CMake rather than having a program for it.

**Comment by cmf028** [comment]
Max size of string literals on msvc is 65535 bytes, so using a raw string literal isn't an option.

include-bin is just a program that gives the same output as xxd -i. I used that instead of xxd because of the need for windows support.

**Comment by slipher** [comment]
> Max size of string literals on msvc is 65535 bytes

Well if only TIMOTHY LOTTES hadn't written so many comments in `fxaa3_11_fp` we'd be golden :stuck_out_tongue:
