### ISSUE TITLE
Material system: GPU occlusion culling doesn't work if `log2( r_customWidth )` is not equal to `log2( r_customHeight )`

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#1248]
If I have material system and `r_gpuOcclusionCulling` enabled, and set the resolution to anything significantly less than my screen resolution, I get something like this. Many or most surfaces are not drawn that should be.
![unvanquished_2024-08-18_202617_000](https://github.com/user-attachments/assets/d7aba46f-1398-4a3f-afb5-6a012695c67b)

**Comment by VReaperV** [comment]
I'm not getting any such issues with a lower-sized window. How are you setting your resolution?
