### ISSUE TITLE
Fog doesn't look right anymore

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#1258]
In 0.51.1, the fog in [`atcshd`](https://users.unvanquished.net/~kai/bunker/pkg/map-atcshd_1.2.2.dpk) looks like this:

![unvanquished_2024-08-24_053651_000](https://github.com/user-attachments/assets/57000e6a-d82e-4fdf-be3c-cf28fbd8f61f)

In 0.54.0 it looks like this:

![unvanquished_2024-08-24_053820_000](https://github.com/user-attachments/assets/e3cc3443-c422-43d3-8d05-97eb69df5c42)

**Comment by VReaperV** [comment]
How do we know it's the later broken and not the former?

**Comment by cu-kai** [comment]
Here is how it looks in Tremulous. Client is Tremfusion 0.99r3 compiled from git: https://github.com/l-uu/tremfusion
![shot0057](https://github.com/user-attachments/assets/3ed6e449-73d0-4d8b-835b-9bea1dbcb2df)

**Comment by VReaperV** [comment]
That's mostly like the first screenshot, thanks.
