### ISSUE TITLE
Portal regression in `for-0.55-sync` branch

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1275]
The origin of camera is not right in `for-0.55.0/sync` branch.

`master`:

![unvanquished_2024-08-31_121936_000](https://github.com/user-attachments/assets/e3b7a0ae-fabb-4084-8f54-935b9969c452)

`for-0.55-sync`

![unvanquished_2024-08-31_121659_000](https://github.com/user-attachments/assets/d8290ebd-bf7d-49da-9449-310f83446a72)

`master`:

![unvanquished_2024-08-31_121944_000](https://github.com/user-attachments/assets/1932eb56-8e09-4b2d-9a70-0f7d29b8c434)

`for-0.55-sync`

![unvanquished_2024-08-31_121709_000](https://github.com/user-attachments/assets/8a8abe7a-9a2b-4104-b02e-d17ed2e75fc0)

**Comment by illwieckz** [comment]
Some merge conflict was probably badly solved when merging `master` over `for-0.55.0/sync`.

**Comment by illwieckz** [comment]
Test scene is `test-portal-recursion 1380 -5 -16 -68 3`.

**Comment by VReaperV** [comment]
It's a map bug, see: https://github.com/Unvanquished/Unvanquished/pull/2910#issuecomment-1912724832.

**Comment by illwieckz** [comment]
So `for-0.55.0/sync` is right but no `master`?

**Comment by VReaperV** [comment]
> So `for-0.55.0/sync` is right but no `master`?

Yes. I'm a bit fuzzy on details, but it was something like `master` ignoring the difference in z-coordinate and just assuming the camera is at the same z... Or something along those lines.
