### ISSUE TITLE
Should the VFS be case-insensitive?

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#1302]
I saw a map where an image failed to load because the file's extension was written in upper case, and was surprised to learn that VFS paths are case-sensitive. I found this odd because everything else (like commands or any sort of config file) seems to be case-insensitive. So making VFS file opening case-insensitive seems more consistent, and might improve asset compatibility. @sweet235 Do you often see case-sensitivity problems when porting Tremulous maps?

Note: this should be fine for dpkdirs on case-sensitive filesystems because we always open VFS files by looking them up in the loaded file list first, rather than blindly passing the path to the OS's open function. We'd just need a 1-line change to PakPath::ReadFile to use the name from the file list rather than the requested name.

**Comment by illwieckz** [comment]
VFS is expected to be case-insensitive in DPK. If it's not, it's a bug to fix.

It would be cool to also have VFS being case-insensitive with DPKdir, but that's a feature request.

**Comment by slipher** [comment]
Fixed (for 0.55) by #1315.
