### ISSUE TITLE
Translucent surfaces rendered in wrong order

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#1319]
On map Watah, these translucent walls on the opposite side of the room appear to be rendered on top of the closer ones. Judging by `r_debugSort` they both have sort order `SS_BLEND0`.
 
![unvanquished_2024-09-20_185101_000](https://github.com/user-attachments/assets/04c61606-9795-482e-b6da-61b845aa7f8d)

**Comment by VReaperV** [comment]
Might be related to #1079. IIRC they should be sorted by distance back to front.

**Comment by slipher** [comment]
Closing as duplicate.
