### ISSUE TITLE
Motion blur is sometimes broken

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1368]
I forgot to create an issue for that but I mentioned there before:

- https://github.com/Unvanquished/Unvanquished/pull/3093

Motion blur is broken

![unvanquished_2024-10-16_052628_000](https://github.com/user-attachments/assets/a938b123-82e6-4fb8-8572-8eecd4248ee8)

**Comment by illwieckz** [comment]
I dislike about not knowing how I reproduced it, but I don't reproduce it anymore.

**Comment by VReaperV** [comment]
Apparently @sweet235 got the same issue recently:
![image](https://github.com/user-attachments/assets/bfb1c760-9e88-4955-8255-1072ad4d79c9)

So the bug is still there.

**Comment by illwieckz** [comment]
I bet it's not a blur bug but a GLSL shader cache bug. Let's re-open it if we reproduce it later after having no one doubt on the GLSL shade cache.

**Comment by VReaperV** [comment]
Did we have any changes to the blur/contrast shaders at the time?

**Comment by slipher** [comment]
#1816 will add a texture barrier especially for motion blur.
