### ISSUE TITLE
The macOS OpenGL 2.1 software rasterizer isn't detected

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1378]
macOS provides a software rasterizer supporting OpenGL 2.1. Despite our engine supporting GL 2.1, the engine doesn't find any OpenGL at all.

On the contrary other software like NetRadiant just finds and uses OpenGL 2.1.

Having this working would be helpful to test the game on macOS virtual machines. On the contrary to physical macOS machines, it's easier to snapshot macOS virtual machines or to only keep versions that doesn't contain extra component than the game itself (a good way to test we are not forgetting to bundle any library, for example).

**Comment by illwieckz** [comment]
I remember that in the past only GL 2.1 was detected by our engine. We had to change something to get an higher version, maybe that change was in our engine, maybe it was in SDL, I don't know.

So maybe there are two ways to request OpenGL 2.1 in another way. Maybe there are two OpenGL libraries and only one of them is supporting the software rasterizer, the one only supporting GL 2.1.

**Comment by slipher** [comment]
Until 2022 I used to test Mac stuff in a virtual machine with the software rendering. To get it to run (at 6 SPF) I had to set a cvar, `r_glAllowSoftware`.

**Comment by illwieckz** [comment]
Oh! And it still works! That said, the textures are a bit glitchy but it runs:

![20241021-035747-000 unvanquished-macos-software-renderer](https://github.com/user-attachments/assets/3375b7c1-5ce1-42d6-89c5-b2e51ba81ee5)

I'll see if I can reproduce the bugs we faced with it, it may help if we can catch them this way.

**Comment by illwieckz** [comment]
That even says it supports emulated OpenGL 4.1. Great!
