### ISSUE TITLE
Can't run daemonded on macOS

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1390]
Can't run `daemonded` on macOS:

```
Warn: Could not bind singleton socket at file:
 "/var/folders/q8/0gyf99wn3ll4nldcx_kczndm0000gn/T/.unvanquished-server-794C07CE3289A50A86A103978DE9DCE5/socket",
 error: "Address already in use" 
```

But `daemon-tty` works and can host a game.

**Comment by slipher** [comment]
I reproduce on Mac M1 mini.  Changing the homepath doesn't help either.

**Comment by slipher** [comment]
Apparently the original `bind` syscall had a name length limit of ~100 characters and no *nix maintainers have bothered to upgrade it since. 

Workaround:
```
mkdir /tmp/fart
TMPDIR=/tmp/fart ./daemonded
```
