### ISSUE TITLE
Broken pulsating shader on map station12

### ISSUE THREAD

**Issue by VReaperV** [DaemonEngine/Daemon#1418]
I remember it working on 0.54, the walls here should be pulsating with different colours:
![unvanquished_2024-11-01_015947_000](https://github.com/user-attachments/assets/107592fb-0750-4fce-90cd-991298584ab6)

Apparently the same should be true for some wall or something outside the alien base.

**Comment by VReaperV** [comment]
Also, this apparently works on the crystals on the wall there, though I haven't looked at what kind of shaders they use/what the difference between them is.

**Comment by VReaperV** [comment]
Nevermind, it's because I had light styles disabled. Still doesn't work with material sysem though.

**Comment by slipher** [comment]
The pulsating walls everywhere on Pulse also don't work. Probably the time-dependent `rgbGen` is the issue.

**Comment by VReaperV** [comment]
> The pulsating walls everywhere on Pulse also don't work. Probably the time-dependent `rgbGen` is the issue.

Which walls are these supposed to be?

**Comment by slipher** [comment]
![unvanquished-pulse-lowprecision-clamping](https://github.com/user-attachments/assets/f4a9e0db-7f9e-4770-bfaf-6ce8e3f45796)

**Comment by VReaperV** [comment]
Thanks, those work too now.
