### ISSUE TITLE
Using PDCursesMod on all systems?

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1454]
We have a `pdcursesmod` submodule for Windows, so this code is always there.

Should we be use it instead of ncurses on Linux and macOS?

Not only we have pdcurses always available in our sourcetree, but building or linking ncurses isn't that straightforward.

For example in the flatpak we disable ncurses because of various errors, and I myself faced many errors in various situations dealing with ncurses for building the engine.

PDCursesMod provides VT support:

- https://github.com/Bill-Gray/PDCursesMod/blob/master/vt/README.md

So I guess everything is there for Linux and macOS.

**Comment by slipher** [comment]
That's OK with me. We should check with Linux users that the quality of implementation lives up to what they get from ncurses. The Windows integration leaves some things to be desired: there is no way to resize the window, scrolling with mouse doesn't work (only page up/down), and the number of colors is small.

**Comment by illwieckz** [comment]
> The Windows integration leaves some things to be desired: there is no way to resize the window, scrolling with mouse doesn't work (only page up/down), and the number of colors is small.

Ah, that is annoying!

If ncurses is much better, maybe we can look at an option to force the uses on pdcurses on Linux system failing to build with ncurses, but use ncurses otherwise.

Distro packages like Arch ones would use system's ncurses dynamic library, while some other packages may use pdcurses.

**Comment by illwieckz** [comment]
Quote from IRC:

```
<illwieckz> perturbed`, I see USE_CURSES is always ON on Windows, what happens if it is forced to OFF?
<perturbed`> probably it doesn't compile
<perturbed`> the alternative code is based on non-curses unix terminal functions
```

I also noticed that `USE_CURSES` was always disabled on macOS with this comment:

> Not supported on mac because the included version is too old

So using PDCusrsesMod on macOS would make possible to uses `-curses` on macOS.

**Comment by illwieckz** [comment]
PDCursesMod for VT has a `resize_term()` function that seem to work like ncurses `resizeterm()` one.

I can resize and scroll, but the colors are less good.

So, using PDCursesMod looks to be a good fallback.

**Comment by illwieckz** [comment]
@slipher I noticed the call to `resize_term` is commented out on Windows in our code, what if we enable it?

The function is named `resize_term()` on PDCursesMod while it is named `resizeterm()` on ncurses.

**Comment by illwieckz** [comment]
Hmm, maybe what we miss on Windows is a code to query the new size.

**Comment by illwieckz** [comment]
Fixed:

- https://github.com/DaemonEngine/Daemon/pull/1455
