### ISSUE TITLE
Lightstyles broken (again)

### ISSUE THREAD

**Issue by VReaperV** [DaemonEngine/Daemon#1471]
On 0.55.2 light styles seem to be broken again somehow. Unlike #1418, I get this issue both with and without material system.

**Comment by slipher** [comment]
Pulse works for me. Example of map with problems?

**Comment by VReaperV** [comment]
Alien default on station12-b7.

**Comment by slipher** [comment]
Works for me. Is it still broken with a clean homepath?

**Comment by VReaperV** [comment]
Nevermind, it's because I had `r_lightStyles` set to `on`, rather than `1`.
