### ISSUE TITLE
Question about Models and lightmaps

### ISSUE THREAD

**Issue by valina354** [DaemonEngine/Daemon#1472]
Do models have lightmapping or not? i cant really tell from the maps that are in unvanquished, i want to make a standalone game using this engine, but my worry is that theres no lightmaps on models, is there or is there not?

something else unrelated is i cant figure out where the compilers are, are there compilers for the maps or are they built into engine itself?

**Comment by VReaperV** [comment]
Models use grid lighting/vertex lighting (if the former is not enabled). Lightmapping only works on BSP geometry and it's computationally infeasible to use it for models, at least in the way that lightmaps are produced for maps. Both can also use dynamic lights.

Maps are compiled with `q3map2`, which is built into various *Radiant tools, and should also be available as standalone.

**Comment by sweet235** [comment]
The map compiler `q3map2` and our editor variant `NetRadiant` are at https://netradiant.gitlab.io.

**Comment by illwieckz** [comment]
If your purpose is to use models as map prefabs (or import a large map made in another editor as a model), the map compiler will compute lightmaps on it. You have to import models as `misc_model` entities in the NetRadiant editor.

For exhaustivity, minor adjustments to what have been said by @VReaperV:

- Animated models (`misc_anim_model` in the editor): always use light grid.
  There is a fallback to display them fullbright on some very _very_ low end devices, the user cannot enable it on purpose.
- Map: use either light map or vertex light (it's a graphics option, vertex lighting is ugly but uses less memory).

The map compiler is not part of the engine as said by @sweet235.

Some extra knowledge around the topic:

- There is a map compiler option to mix lightmap and vertex lighting on world surfaces to save on lightmap size, but this is not recommended as it doesn't allow to benefit from improved texturing (normal map, specular map, etc.) with vertex lighting. It was a cool trick in early year 2000, but doesn't make sense if you want the map to look better than a map made in the early year 2000.
 
- It's possible to tell materials to force the use of vertex lighting on the map surfaces using it, it suffers from the same limitations and it's usually not really useful outside of backward compatibility with existing legacy maps.

- When a model is used as part of a map and not expected to be animated (a static model as a `misc_model` in the editor), it's possible to let the map compiler bake the model in the map geometry and then use lightmaps (or vertex lighting) on it. The model just becomes a kind of prefab, and the engine doesn't know there was a model in the map editor, the engine just sees lightmapped map surfaces.

In the future we may enable lightgrid on some specific  map surfaces, like movable doors or trains. They are not considered animated models, they are map surfaces that move. Making them use lightgrid would avoid some glitches like a baked shadow to moving with a door. Almost everything is implemented for this, we just focused on other things so we still have to finish this.

**Comment by valina354** [comment]
Ok, thanks for the help everyone.

**Comment by illwieckz** [comment]
The map compiler can bake models in those formats as lightmapped static models in the map:

- IQM
- MD3
- OBJ
- ASE

and maybe some obscure others.

There is a tool to convert from glTF to IQM and to convert from MD5mesh to IQM named `iqmtool` provided by FTE:QW:
https://wiki.unvanquished.net/wiki/Tools/IQM#iqmtool

I have verified this `iqmtool` properly converts from MD5Mesh to IQM but haven't tested glTF to IQM.

For animated models in the game (using the light grid), you can use:

- IQM
- MD5mesh
- MD3 (not skeletal, so IQM is preferred)

More details can be found here: https://wiki.unvanquished.net/wiki/Formats/Model

And welcome around! 👋️
