### ISSUE TITLE
Drop VM file handle support?

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#164]
There is code that allows the VMs to open an FS::File that is backed by a real Unix file descriptor, which can be directly operated on by the gamelogic. It works, but is used by nobody (all VM code is using the older API where each operation is an engine call operating on the table in src/engine/qcommon/files.cpp).

Reasons to delete it other than being unused:
- Potential difficulty in porting if we move off of NaCl. 
- Sketchy or at least difficult to understand from a security point of view.

The main reason to keep it would be if we expected to have a use case for high-volume file I/O inside the gamelogic.

**Comment by DolceTriade** [comment]
I wonder if the file support can be extended to file support to allow moving network code into the VM?

**Comment by slipher** [comment]
I don't know, not sure if there's any way to use a socket as a file on Windows.

Even if we do want to have file descriptors for network I/O, it doesn't mean we need to support it for any files in the homepath.

**Comment by slipher** [comment]
Done in #250.
