### ISSUE TITLE
debug message about missing sound file not displayed

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#166]
I noticed it while working on #165, it looks like there is code to display a debug message about missing sound file, but I see nothing displayed.

https://github.com/DaemonEngine/Daemon/blob/be89425dd92889b0f965d6890a804148b7832711/src/engine/audio/SoundCodec.cpp#L105

How to reproduce:

- run engine this way: `./daemon -set logs.logLevel.default debug`
- play a non existent sound this way: `/playSound meh`

**Comment by slipher** [comment]
Well it's working as designed... `logs.logLevel.default` is not the default log level, but rather the level of the default logger, that is, the logger used for `Log::(Notice|Warn|Verbose|Debug)`. You can't see the message without setting `logs.logLevel.audio`.

**Comment by illwieckz** [comment]
Oh you're right, it works. Well, is there a way to set a debug level with one variable?
