### ISSUE TITLE
ClipWinding: MAX_POINTS_ON_WINDING with moteof (q3) and oasis (wolfet) maps

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#169]
Both `ioquake3`[🗗](https://github.com/ioquake/ioq3/blob/d068e1dce174d2631d2d760d1d729a9d1d4151b8/code/qcommon/cm_polylib.h#L31) and `daemon` defines `MAX_POINTS_ON_WINDING` to `64`:

https://github.com/DaemonEngine/Daemon/blob/be89425dd92889b0f965d6890a804148b7832711/src/common/cm/cm_polylib.h#L43

But while ioquake3 loads “[The Edge of Forever](http://www.simonoc.com/pages/design/sp/moteof.htm)” with that setting, dæmon requires this value to be set to `134`.

If this value is less or equal to `133`, this message is printed on console and the map loading aborts:

```
Warn: ClipWinding: MAX_POINTS_ON_WINDING 
```

There is no reason this map can't be loaded with a max set to `64`.

On a side note, because the problem aborts the map loading, this problem must be raised as an error instead of a warning.

## How to reproduce

Download map [here](https://dl.illwieckz.net/b/daemon/bugs/max-points-on-winding/map-moteof_0%2Bfinal2.dpk) (it's just a dpk repack of the [original pk3 for quake3](http://www.simonoc.com/files/maps/sp/moteof_final2.zip)), load it with `+devmap moteof`.

**Comment by illwieckz** [comment]
For some unknown reason, ioquake3 has these functions in `cm_polylib.c` but dæmon does not have them in `cm_polylib.cpp`:

```
RemoveColinearPoints
WindingPlane
WindingArea
WindingBounds
WindingCenter
ReverseWinding
ClipWindingEpsilon
AddWindingToConvexHull
```

And dæmon only contains half of this one:

```
WindingOnPlaneSide
```

See:  
- [ioquake3/cm_polylib.c](https://github.com/ioquake/ioq3/blob/bf4c7a0341ae000188c4e226f55813f7e80a1dfa/code/qcommon/cm_polylib.c)
- [dæmon/cm_polylib.cpp](https://github.com/DaemonEngine/Daemon/blob/1eb96ce1038474d667f402a46b4c1c8267c1b0af/src/common/cm/cm_polylib.cpp)

**Comment by illwieckz** [comment]
The file that are in ioquake3 but not in dæmon were removed in f9d69b9 because being unused.

Some are are dead code in ioquake3 too:

```
RemoveColinearPoints
WindingCenter
ReverseWinding
ClipWindingEpsilon
AddWindingToConvexHull
```

But ioquake3 still uses those:

```
WindingPlane
WindingArea
WindingBounds
```

**Comment by illwieckz** [comment]
I really have no idea about how to debug this…

**Comment by illwieckz** [comment]
On a side note, in the past it was an error, not a warning (Unvanquished 0.35):

[![max points on winding](https://dl.illwieckz.net/b/unvanquished/bugs/max-points-on-winding/unvanquished_2019-12-02_033147_000.png)](https://dl.illwieckz.net/b/unvanquished/bugs/max-points-on-winding/unvanquished_2019-12-02_033147_000.png)

It's better to tell the user a cryptic error than just failing silently without notice.

**Comment by illwieckz** [comment]
Unvanquished 0.6.0, the oldest release I have, already raises `ClipWinding: MAX_POINTS_ON_WINDING` on this map while Tremulous does not.

**Comment by illwieckz** [comment]
Also, ET:XreaL 0.3.0 20111110 did not have the bug, ET:Legacy does not have it. This looks to be very specific to our tree.

**Comment by illwieckz** [comment]
With TremFusion 0.99r3_R1422 (linux-x86_64 Jul 6 2009)

I get:

```
********************
ERROR: Hunk_AllocateTempMemory: failed on 3554440
********************
----- Server Shutdown (Server crashed: Hunk_AllocateTempMemory: failed on 33554440) -----
```

**Comment by illwieckz** [comment]
The error is raised by `ChopWindingInPlace()` from `cm_polylib.cpp`.

This function is called in multiple places:

in `cm_load.cpp`: `CMod_CreateBrushSideWindings()` (1 time)

in `cm_trace.cpp`: `CM_DrawDebugSurface()` (1 time)

in `cm_plane.cpp`: `CM_AddFacetBevels()` (2 times), `CM_ValidateFacet()` (1 time)

The issue occurs when `ChopWindingInPlace()` is called by `CMod_CreateBrushSideWindings()` in `cm_load.cpp`, not in other cases.

Note that the debug code was probably not tested as I suppose it's not part of the default route, but we know the issue does not occurs when called by `CM_AddFacetBevels()` and `CM_ValidateFacet()`.

**Comment by illwieckz** [comment]
This `CMod_CreateBrushSideWindings()` function seems to not exist in `ioquake3` or `etlegacy`, or not with that name.

**Comment by illwieckz** [comment]
if I allocate the various arrays formerly using `MAX_POINTS_ON_WINDING` as number of elements by using `4 * MAX_POINTS_ON_WINDING` instead, and keep the `> MAX_POINTS_ON_WINDING` failure test for everything but that `CMod_CreateBrushSideWindings()` function, the map loads.

So, we know we don't have regression in code inherited from quake3.

We fail on what looks to be original code from XreaL. Maybe this original code is not faulty but requires a larger array, who knows?

**Comment by illwieckz** [comment]
I'm not finding this `CMod_CreateBrushSideWindings()` function, neither in XreaL, neither in ET:XreaL.

**Comment by illwieckz** [comment]
After having found it in Dusan's OpenWolf Qio rip-off, I highly doubted this was coming from this. Especially since Qio did not have this code either. So I've looked to XreaL again. There is multiple branch of it.

And I found it:

```sh
git log -S 'CMod_CreateBrushSideWindings'
```
```
commit 7a41d76a79ef6015d0bee98350764e539adf3fb9
Author: trebor_7 <trebor_7@8d6dca30-e10d-0410-ba00-f2efb4c278cc>
Date:   Thu Dec 18 22:24:20 2008 +0000

    merged tremulous' 1.1.0 math and collision code
```

Note that this git commit reference probably only exists on my computer since it's probably a git repository converted from some forgotten svn or even cvs repository somewhere on the internet.

What's interesting is that this commit claims to have imported this from Tremulous 1.1.0, but the various Tremulous builds I tested did not suffer the issue.

**Comment by illwieckz** [comment]
Both Tremulous 1.1.0 and Tremulous GPP are able to load the map.

**Comment by illwieckz** [comment]
So, this is 2720 revision in old svn XreaL repository: https://sourceforge.net/p/xreal/svn/2720

Focus on this function: https://sourceforge.net/p/xreal/svn/2720/tree//trunk/xreal/code/qcommon/cm_load.c?diff=519a30865fcbc9773662b0c7:2719

I don't know if the code from that revision works, but newer versions of XreaL seems to not trigger the bug.

**Comment by illwieckz** [comment]
I also get this issue with Wolfenstein: Enemy Territory map:

```
Warn: ClipWinding: MAX_POINTS_ON_WINDING 
```

But ET:Legacy loads it well.

**Comment by illwieckz** [comment]
Do someone has something against using an higher arbitrary value as workaround? Like `256`. At least we know the `64` limit was set for another code than the one that is currently hitting this limit.
Do someone understands this code?

@zturtleman, as a legendary wizard from mythical kingdom of the third id, maybe with some luck you would have an opinion on the matter?

**Comment by zturtleman** [comment]
I don't know the polylib code other than it's also used in [q3map2](https://gitlab.com/xonotic/netradiant/-/blob/master/tools/quake3/common/polylib.c) and BSPC. They might use the dead code in ioquake3's cm_polylib.c.

If the code is identical to ioquake3 maybe the error is caused by float related compiler flags. Similar to x87 FPU vs SSE2 (default on x86_64) float differences for BSP patch planes (https://github.com/ioquake/ioq3/issues/186).

ioquake3 x86_64 has `-ffast-math` which may cause non-standard float behavior. It looks like it's enabled in [DaemonFlags.cmake](https://github.com/DaemonEngine/Daemon/blob/a4a2e7e7f7401b6ce0c8e571e612f39b866d0178/cmake/DaemonFlags.cmake#L165). I don't know what causes Daemon to behavior different from ioquake3.

Maybe try to compare generated assembly code for ioquake3 and Daemon's cm_polylib functions.

**Comment by illwieckz** [comment]
Hi! Thank you for your answer. The issue is in some code that we don't inherit from ioquake3 (see this comment: https://github.com/DaemonEngine/Daemon/issues/169#issuecomment-578312275) it looks like to have been introduced in XreaL but was borrowed from Tremulous (https://github.com/DaemonEngine/Daemon/issues/169#issuecomment-578315892). I confirm this code does not exist in ioq3 master but exists in Tremulous 1.1.0.

If you don't understand this code, well, too bad for me and sorry to have pinged you then. I'm looking for someone who can help me to either fix the issue, either give me some clue to where the issue can or give me some help in understanding what the code does, either tell me it's not an issue. Since Tremulous had the code without failing with this `64` limit, it looks to be an issue anyway.

Unfortunately we can't compare this code to ioq3, but we can compare to Tremulous or XreaL.

**Comment by illwieckz** [comment]
Note: disabling `-ffast-math` does not help.

**Comment by illwieckz** [comment]
Worked around in #312.
