### ISSUE TITLE
GitHub organization structure.

### ISSUE THREAD

**Issue by Viech** [DaemonEngine/Daemon#2]
Right now we have
- a set of owners,
- a team of developers who can write to all repositories (@DaemonDevelopers/developers), and
- teams for both Unvanquished and Xonotic.

I added the latter two teams so that both Unvanquished and Xonotic admins can add developers without the other side wondering who this new person is and where they come from. (For instance, I just added @illwieckz who is already an Unvanquished developer.) These teams do not come with any additional permissions. We can add more such teams (e.g. Independent) when the need arises.

I think we do not need the Developers team, as we can just give write access to all repositories to every organization member, without also requiring them to be on any team. What do you think?

**Comment by mbasaglia** [comment]
Seems fair enough to me

**Comment by Kangz** [comment]
+1

**Comment by Viech** [comment]
Done, all members have write access to all repositories now.
