### ISSUE TITLE
drop forward renderer, focus on tiled one

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#236]
It would be good to drop the forward renderer to not have to maintain two renderers. The tiled renderer seems to be the default for age, so it looks ok, and if there is issues in it, they must be fixed.

In #193 @cmf028 said there: https://github.com/DaemonEngine/Daemon/pull/193#issuecomment-508963612

> The tiled lighting path is currently disabled when realtime shadows are enabled. To fix this, we need to render our shadows into a single tiled shadow map like Doom (2016) does so we can access it when we loop over the lights here.

This seems to be the only reason why people would look for the forward renderer today. In anyway realtime shadows are only good in screenshots, when they work, if they work. So I would not be against removing the option for them from preference dialog until we got them working on tiled renderer.

**Comment by slipher** [comment]
Following the old discussions on this, I did https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/commit/c16b3b298ab5fe5dba9caf7176ee130e9fde35a8 which prevents the `r_dynamicLight` cvar from being set to the value that causes the forward renderer to be used from the menu.

Are there other relevant cvars besides that?

**Comment by bmorel** [comment]
ping

**Comment by illwieckz** [comment]
We need some wizard able to do that:

- https://github.com/DaemonEngine/Daemon/issues/242
- https://github.com/DaemonEngine/Daemon/issues/241

We can also drop the current implementation of them because it's now unused. I don't know how much of the current implementation can be reused though.
