### ISSUE TITLE
new-style CVAR_LATCH cannot be used at startup (requires restart… at startup)

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#279]
New-style CVAR_LATCH was just implemented (#272) and `fs_legacypaks` now uses this feature (#264). By toying with Xonotic's [daemon-glue](https://gitlab.com/xonotic/daemon-glue) I've discovered that if I set a new-style latched cvar at startup by command line, it requires to restart again.

And if `fs_legacypaks` is required to load the game code (because it is stored in `xonotic-data.pk3dir`), the game would abort before being able to restart.

**Comment by slipher** [comment]
I expected this to be primarily used for rendering cvars, so I did not take care about making them apply to the main menu when implementing (not that I disagree that it's legitimately a bug).

Maybe just remove CVAR_LATCH from fs_legacypaks? I don't really see why it should be applied. If you wanted to load some legacy paks after changing the value to true, would that actually be impossible?

**Comment by illwieckz** [comment]
In fact all I wanted was a message telling me to restart (same for `fs_maxSymlinkDepth`).

**Comment by illwieckz** [comment]
Maybe we can implement a simpler `CVAR_RESTART` or something like that, without latched behavior, just to trigger a "please restart" notice.

**Comment by slipher** [comment]
Out of curiosity, what mistake are you trying to prevent yourself from making? In what scenario would you unsuccessfully attempt to load paks here that would have been prevented by restarting?

Anyway, I recommend to just get rid of the flag on this cvar, since fixing this is too boring for the moment.

**Comment by illwieckz** [comment]
Yep, I'll revert my commit, because that's the simplest way to fix the issue.

I simply thought it would be better to tell the user what to do, but the cost seems too high at this point.

**Comment by illwieckz** [comment]
Note that `fs_maxSymlinkDepth` is also affected by the issue and is typically something an user can set to fix a missing texture error. While it's not a rendering cvar, it can be used because of graphical issue and it would be better if the user is told to restart to make sure he does not think the feature is broken because no immediate change is seen. User will not necessarily understand how it works under the hood and that files are not loaded on the fly.

Since symlinks may be used on any file including required files to load the game (something that is not recommended but doable), it is better to just disable it for the moment.
