### ISSUE TITLE
Unhandled exception (St12out_of_range) when displaying map list window if dpk with small name is in path

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#285]
I don't know from which server it comes, but if that a dpk file with a small file name is in path, the engine triggers this exception and quits:

```
Warn: Unhandled exception (St12out_of_range): basic_string::substr: __pos (which is 4) > this->size() (which is 2) 
```
The only requirement to reproduce the bug seems to have this kind of file in path to crash the engine while clicking on “_Start local/LAN game_”:

[![Unhandled exception (St12out_of_range)](https://dl.illwieckz.net/b/daemon/bugs/dpk-unhandled-exception/20200205-034900-001.unvanquished-dpk-unhandled-exception.png)](https://dl.illwieckz.net/b/daemon/bugs/dpk-unhandled-exception/20200205-034900-001.unvanquished-dpk-unhandled-exception.png)

I reproduce the bug on released `0.51.1` and `master`.

**Comment by illwieckz** [comment]
I noticed the error also occurs when the file is present at startup but removed from filesystem before the link is clicked.

**Comment by illwieckz** [comment]
This is a way to create a `a_0.dpk` that reproduces the bug:

```sh
cd ~/.local/share/unvanquished/pkg
(mkdir empty; cd empty; 7z a -tzip -mx=9 ../a_0.dpk .; cd ..; rmdir empty)
```

We note the issue is about a faulty range of 4, while the file base name lenght is smaller than 4. This may be related to the test for `map-` prefix which has a lenght of 4.

**Comment by DolceTriade** [comment]
Can you get a backtrace of this? The exception should trigger gdb to stop.

**Comment by illwieckz** [comment]
I was running on gdb when I first faced it and gdb caught nothing.

**Comment by slipher** [comment]
Try using the command `catch throw` in gdb (you might want to do this after starting the application since it might throw some exceptions in normal initialization).

**Comment by illwieckz** [comment]
Creating a dpkdir is easier and enough:

```sh
mkdir -p ~/.local/share/unvanquished/pkg/a_0.dpkdir
```
