### ISSUE TITLE
Wrong default colormap blend

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#289]
The bug is not new, but was hidden by the bug fixed in #277 (_glsl/lightmapping: fix terrain alpha blending for collapsed materials_).

This bug was already there before in vertex lighting mode.

This is how it must look:

[![wrong colormap blend](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_005235_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_005235_000.jpg)

This is now it looks now on light map lighting mode:

[![wrong colormap blend](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_002823_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_002823_000.jpg)

This is how it already looked like on vertex lighting mode before #277:

[![wrong colormap blend](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_080750_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_080750_000.jpg)

This is how it looks like on vertex lighting mode if I apply the same buggy workaround that was applied in lightmap lighting mode before #277 

[![wrong colormap blend](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_121039_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_121039_000.jpg)

Don't mind the bizarre artifacts for now, that's another bug I have not yet investigated, but definitely another bug (looks to have been introduced between `0.50.0` and `0.51.1`).

The bug we talk about always has been there, this is how the same map looked like on Unvanquished 0.6.0 and 0.50.0 in vertex lighting mode. That was already too much darky, but we also see our engine is now more darky with newer artifacts that was not there at first, that's probably another yet unknown bug:

[![wrong colormap blend](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_115727_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_115727_000.jpg)

[![wrong colormap blend](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_113839_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_113839_000.jpg)

So the bug fixed in lightmap glsl in #277 looks to have been a workaround for an old bug living in others glsl shaders.

This bug only occurs on some legacy materials. It's related to the various guesses the engine does to detect the right color blend to apply, the problem probably living in that test:

https://github.com/DaemonEngine/Daemon/blob/94823acb06899fb7a5d33214b97742630712e4da/src/engine/renderer/tr_shader.cpp#L2984-L2995

If `stage->rgbGen` is always set to `colorGen_t::CGEN_IDENTITY`, both lightmap lighting and vertex lighting looks ok (but then it breaks some other textures that legitimately relied on this test to set the other type).

**Comment by slipher** [comment]
Glorious. We can create a game which can be played without `/r_gamma 2` :stuck_out_tongue_closed_eyes:

**Comment by illwieckz** [comment]
Note that this bug made the map darker than current engine with `/r_gamma 1`:

Current engine with bug being awaken from a 14 years sleep by patch enabling alphagen in diffuse code path:

[![broken engine](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_115727_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-11_115727_000.jpg)

Current engine, gamma 1, (stock `0.51.1` or `master` with fixed bug):

[![stock engine](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-13_105604_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-13_105604_000.jpg)

Current engine, gamma 1, colorspace correction and dithering to reduce color banding a bit:

[![next-gen engine](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-13_101612_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-13_101612_000.jpg)

This map was made for Tremulous in 2007, this is the 2007 build by KOsAD, not some extensive rebuild I did (lightmap file dates are `2007-03-12`, so those lightmaps will be 13 years old in one month).
