### ISSUE TITLE
Organization name change.

### ISSUE THREAD

**Issue by Viech** [DaemonEngine/Daemon#3]
@DaemonDevelopers/owners, what's your thoughts on renaming this organization to `DaemonEngine`? It's shorter, which is nice because the current name is too long to fully display inside "Repositories you contribute to", and it's also more descriptive, showing that this organization hosts a (game) engine and its tools. (Unfortunately, just `Daemon` is taken by a GitHub user.)

Right now it's easy to make such a rename as the engine wasn't fully outsourced from Unvanquished just yet, but this is bound to happen very soon.

**Comment by mbasaglia** [comment]
TBH I think we should rename daemon altogether since it's an unfortunate generic name.

**Comment by Kangz** [comment]
+1 for DaemonEngine, I don't have a strong opinion about the name "Daemon" itself.

**Comment by illwieckz** [comment]
+1 there is no need to put the “Developer” word in a GitHub organization name for a game engine. It's like naming it _DaemonGameEngineGitHubOrganizationForPeopleWhoContributeGameEngineCodeUsingGitOnGitHub_.

About _Dæmon_ itself… well, is'nt true both _Unvanquished_ and _Dæmon_ were [kind of placeholders](https://forums.unvanquished.net/viewtopic.php?f=4&t=1392) at first? But to me they are endearing now, even if I still don't know how to pronnounce _Unvanquished_. :grin: 

Even if both _Daemon_ and _DaemonEngine_ is very generic, Google will know how to sort out _Daemon Engine_ searches.

**Comment by Viech** [comment]
I like `DaemonGameEngineGitHubOrganizationForPeopleWhoContributeGameEngineCodeUsingGitOnGitHub`, it's even more descriptive than my original propsal.

Jokes aside, I'll rename this organization to `DaemonEngine` if none of the @DaemonDevelopers/owners vetos against it in the next two days. I hope this won't hurt our decoupling efforts, @illwieckz?

**Comment by illwieckz** [comment]
> I hope this won't hurt our decoupling efforts, illwieckz?

There is no problem at all, it just means I will wait two more days to merge my PR so I can rewrite it with the new submodule path to get it right from the start, and by the way, I will be off for the next 24 hours, so it's not a problem at all. :wink:

**Comment by Viech** [comment]
It is done. Welcome to @DaemonEngine.
