### ISSUE TITLE
Translucent texture rendered above fog

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#314]
First seen in https://github.com/Unvanquished/Unvanquished/issues/799

See the ice stalactites on the gauntry (in background):

[![translucent on fog](https://dl.illwieckz.net/b/daemon/bugs/translucent-on-fog/unvanquished_2020-04-12_045607_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/translucent-on-fog/unvanquished_2020-04-12_045607_000.jpg)

**Comment by VReaperV** [comment]
This might be some incorrectly set shader sort since we do depth->opaque->fog->translucent. Or maybe we just need another pass before fog and after opaque, since stalactites probably are translucent.

**Comment by VReaperV** [comment]
I decided to check if it's still true...

![image](https://github.com/user-attachments/assets/5afcf7d0-a6e2-407c-ae9f-a4043c33be0a)

On the bright side, it's no longer rendered above fog.

**Comment by VReaperV** [comment]
Confirming the original bug is still there.

**Comment by VReaperV** [comment]
> This might be some incorrectly set shader sort since we do depth->opaque->fog->translucent. Or maybe we just need another pass before fog and after opaque, since stalactites probably are translucent.

So the stalactites are, in fact, translucent.

**Comment by VReaperV** [comment]
The `implicitMask` is indeed not working, because the alpha threshold is being set to 1.5, i.e the default value.

**Comment by VReaperV** [comment]
Looks like the shader gets sorted as opaque and I'm not seeing it being used when stepping through the `RB_RenderDrawSurfaces()` code for translucents, but I see it being rendered after the global fog in a frame debugger...

**Comment by VReaperV** [comment]
They also don't write to depth, even though they should.

**Comment by VReaperV** [comment]
Oh wait, I was looking at the wrong shader lol.

**Comment by VReaperV** [comment]
So this is the shader in question:

```
surfaceparm alphashadow
cull none
{
    map textures/snow/alpha_ice2s.tga
    blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
    rgbGen vertex
}
```

It might be that `alphashadow` is supposed to turn alpha testing on here, but it doesn't.

**Comment by VReaperV** [comment]
I've watched some wolf ET videos and it seems the icicles there are also rendered above fog, the only difference is ours are rendered darker for some reason (on the original screenshot the ones closer to the view are rendered as they should, unlike the ones on te gantry, now both are like the ones on the gantry).

**Comment by VReaperV** [comment]
The shader is set to do rgbgen vertex, and these are the vertex colours used by those surfaces:
With default overbright settings:
![image](https://github.com/user-attachments/assets/8deaed74-7aa6-4fc9-a224-d1473f166db5)
With `r_overbrightDefaultClamp on`:
![image](https://github.com/user-attachments/assets/e580e639-7da1-467b-bcb5-913c6e7983c9)

So this has something to do with overbright.

**Comment by VReaperV** [comment]
The first screenshot has the original vertex colours, so they're being rendered correctly based on that.

**Comment by VReaperV** [comment]
Closing since the original issue is a map/shader bug, not an engine one.
