### ISSUE TITLE
Light color restoration algorithm produces awful results when using lightdir from lightgrid

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#324]
This use case occurs when the engine is attempting to do normal/specular compute using lightmap light color but lightgrid light direction:

[![lightgrid lightcolor restoration](https://dl.illwieckz.net/b/daemon/bugs/lightgrid-lightcolor-restoration/unvanquished_2020-04-23_170140_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/lightgrid-lightcolor-restoration/unvanquished_2020-04-23_170140_000.jpg)

[![lightgrid lightcolor restoration](https://dl.illwieckz.net/b/daemon/bugs/lightgrid-lightcolor-restoration/unvanquished_2020-04-23_171325_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/lightgrid-lightcolor-restoration/unvanquished_2020-04-23_171325_000.jpg)

[![lightgrid lightcolor restoration](https://dl.illwieckz.net/b/daemon/bugs/lightgrid-lightcolor-restoration/unvanquished_2020-04-23_171344_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/lightgrid-lightcolor-restoration/unvanquished_2020-04-23_171344_000.jpg)

See #299 about lightcolor restoration, #299 is the deluxemap counterpart of this bug.

The bug may also be related to #320.

We must find a better algorithm or a variant of it for that special use case if we want to support it.

We may want to support it for two reasons:

1. reduce the complexity of the code, avoid intrusive hacky ifdefs everywhere.
2. enable normal mapping on legacy maps.

**Comment by hypov8** [comment]
now that i think back, i previously have a similar issue in kingpinQ3. random artifacts in deluxmap
i found it was a compiler issue.
if you compile with thread 1 it fixed the issue. there is some bug when its laying down the UV map for patches. it would overlap existing data. hence why u see an inverted deluxmap. because it not the only face using the texture space.

to use multi thread still. i just set 1 thread before running
Sys_Printf("--- MapRawLightmap ---\n");
RunThreadsOnIndividual
then set back to previous value

**Comment by VReaperV** [comment]
This issue is no longer true, especially as we never use lightgrid for BSP surfaces, unless `r_lightMode` is set to 2, which is a cheat value. Even with it set to 2, I'm not seeing the issues in the screenshot anymore.

**Comment by illwieckz** [comment]
It is still true, and the code is still there and used. 🙂️

Here:

https://github.com/DaemonEngine/Daemon/blob/559e2df4bd6dd51943d742f21a3cdef7cd47e677/src/engine/renderer/glsl_source/lightMapping_fp.glsl#L130-L133

https://github.com/DaemonEngine/Daemon/blob/559e2df4bd6dd51943d742f21a3cdef7cd47e677/src/engine/renderer/glsl_source/lightMapping_fp.glsl#L158-L182

There are two kind of informations stored in light grid:

1. Light color
2. Light direction

The `r_lightMode 2` option is only about light color.

That bug can be reproduced on glass surfaces in default human base of station15 map.

**Comment by illwieckz** [comment]
Hmm, maybe we don't get the light direction from light grid. But the “light color restoration algorithm” still “produces awful results“.

**Comment by VReaperV** [comment]
> It is still true, and the code is still there and used. 🙂️

BSP surfaces never use deluxe grid, they either use deluxe map or none.

**Comment by illwieckz** [comment]
Hmm, maybe I confused with the remaining bug of light color restoration from deluxe map (as seen in station15).
