### ISSUE TITLE
Game models are sometime darker than the environment suggests

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#325]
Look at the reactor and the machinegun turret, they are too dark for the light we must expect at this place given the light on the lightmap:

[![darky game models](https://dl.illwieckz.net/b/daemon/bugs/darky-game-models/unvanquished_2020-04-23_171446_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/darky-game-models/unvanquished_2020-04-23_171446_000.jpg)

This issue seems to be related to #324, game models always used lightgrid light direction. But in that case it also uses lightgrid color so there is not attempt to restore the color from lightmap and light direction (see #320).

**Comment by bmorel** [comment]
For info, the map is terminus

**Comment by illwieckz** [comment]
Those models are lit with the lightgrid, I now consider this as an asset issue (the shipped lightgrid being too dark there).

At best this can be a bug in q3map2, but this map has no source, so no one can reproduce the bug on q3map2 side. One would open an issue on NetRadiant issue tracker if he reproduces it while compiling a map.
