### ISSUE TITLE
predator cloak bug

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#33]
During yesterday's community game, tvezet talked about a rendering bug he experienced (quotes from in-game talk):

> illwieckz: hi tvezet :-)
> tvezet: hi
> tvezet: is it a known bug that entities as buildings or player arent shown correctly if there are flames or pulse rifle shots? it looks pretty much like the predator camouflage
> illwieckz: that bug looks to nothing known
> illwieckz: can you take screenshot of that?
> tvezet: yes ill try
> tvezet: did some screenshots of that
> tvezet: combined with framerate dropping badly
> tvezet: 11fps

tvezet taken some screenshots and reported the bug on [forum](https://forums.unvanquished.net/viewtopic.php?f=6&t=2139):

> After several failed attempts to run the game on debian wheezy i have finally installed an ubuntu 16.04 and now the game is running fine with more or less constant 60fps.
> However sometimes it drops to about 20-30fps or even less and entities like players and buildings disappear leaving something looking like the emptiness outside the map. It often occurs when there is much stuff around and every time someone uses a flame thrower or pulse rifle.
> Some sreenshots:
> ![image](https://www2.pic-upload.de/img/33976964/unvanquished_2017-09-24_231533_000.jpg)
> ![image](https://www2.pic-upload.de/img/33976966/unvanquished_2017-09-24_231535_000.jpg)
> ![image](https://www2.pic-upload.de/img/33976965/unvanquished_2017-09-24_231547_000.jpg)
> ![image](https://www2.pic-upload.de/img/33976967/unvanquished_2017-09-24_233122_000.jpg)
> Any suggestions how to solve this?

**Comment by illwieckz** [comment]
See Unvanquished/Unvanquished#1024 for hardware details etc.

**Comment by bmorel** [comment]
Images are dead.

**Comment by bmorel** [comment]
related unvanquished issue has been closed, there are no pictures showing the bug.

> It often occurs when there is much stuff around and every time someone uses a flame thrower or pulse rifle

We've seen **a lot** of firebomb spamming those days in the PvE games, and this never happened.

I am pretty sure this can be closed.

**Comment by slipher** [comment]
Yeah haven't heard about this one in years, let's close it.
