### ISSUE TITLE
void speed bug

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#34]
When you move fast (like a goon can), the skybox sometime fills itself with pure white color as if it was void. It's very easy to reproduce on _atcshd_ map:

![void speed](http://dl.illwieckz.net/b/unvanquished/bugs/void-speed/unvanquished_2017-09-26_233610_000.jpg)

See also this [video](http://dl.illwieckz.net/b/unvanquished/bugs/void-speed/20170926-231900-000.unvanquished-void-speed-effect.webm).

This shot and this video were taken while running Unvanquished 0.50.0.

By the way, I only noticed it recently (some month ago), so it can be a driver regression on my end.

For reference:

```
$ lspci -nn | grep VGA
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii XT / Grenada XT [Radeon R9 290X/390X] [1002:67b0] (rev 80)
```

```
$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) R9 390 Series (AMD HAWAII / DRM 3.15.0 / 4.12.11-20170910-illwieckz+, LLVM 5.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.1 - padoka PPA
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.2.1 - padoka PPA
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.2.1 - padoka PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

**Comment by illwieckz** [comment]
You can notice how it expands also from bright spots like stars.

**Comment by illwieckz** [comment]
It can be noticed in forlorn map too (but the sky becomes dark instead).

**Comment by illwieckz** [comment]
When I disable blooming (`r_bloom 0`), the screen does not fill with white, be I can clearly notice the “endless mirror” effect like void used to be:
[![void speed](http://dl.illwieckz.net/b/unvanquished/bugs/void-speed/unvanquished_2017-09-28_143320_000.jpg)](http://dl.illwieckz.net/b/unvanquished/bugs/void-speed/unvanquished_2017-09-28_143320_000.jpg)

**Comment by illwieckz** [comment]
It's very easy to reproduce it with a goon in plat23's outside too.

**Comment by t4im** [comment]
Can confirm this. During a dev game this occured right after a goon-pounce.
This is somehow related to motionblur. The interesting part is, that at the end of the pounce it stayed like this, despite being motionless, but even during radial movement.

It only reseted the blur after some backward motion (strafing or forward moving wasn't possible at the time).

**Comment by necessarily-equal** [comment]
I agree that it actually happens on other parts of the map, basically anything that's displayed next to the sky (except the stellar background).

This seems to be related to motion blur, as disabling it makes the effect disappear. The bug is still here with 0.52.0/sync.

My guess is that the motion blur is making a lot of copy and stack them on each other, but doesn't handle "there is nothing" as a copy.

**Comment by necessarily-equal** [comment]
I've got a fix :P

https://github.com/DaemonEngine/Daemon/pull/410

**Comment by necessarily-equal** [comment]
the fix has been merged, I believe this can be closed.

**Comment by illwieckz** [comment]
Right.
