### ISSUE TITLE
Looking for a name for a cvar to make system-specific workarounds disableable

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#360]
We already have one workaround for buggy nvidia driver (see #63), but it would be useful to be able to disable the workaround to check if the bug still occurs or on which hardware/software combination it occurs.

I would like to see other workaround implemented, like:

- forcing `r_picmip 1` for systems having 2GB or less of RAM. I verified Dæmon running on a system with 2GB of ram (even running the lightweight IceWM desktop on Linux) cannot load `plat23` map with full size textures without being killed by the OS to recover from an _Out Of Memory_ error;

- forcing `r_picmip 1` for systems having less than 512MB of VRAM, I verified systems having 256MB or 384MB of VRAM cannot load `plat23` map with full size textures without hanging the whole computer (on Linux).

There may bee other workarounds to implement to make sure players do not end with a game being silently killed by the OS or the hardware going mad in situation we now well know.

But I'm not really happy with the idea of not being able to disable those workarounds, I want to be able to check in the future if a given workaround is still legit or not. A cvar would be very good for such purpose. The idea would be to have a boolean cvar being enabled by default (disabling the cvar would disable the workarounds).

I'm lacking imagination right now, so if you have an idea, please make suggestions!

**Comment by illwieckz** [comment]
I say « hardware specific » at first, but the same cvar would cover system specific bugs in general, like the nvidia driver one.

**Comment by slipher** [comment]
How about `useHardwareWorkarounds`. Yeah OK an Nvidia driver technically isn't hardware, but close enough.

**Comment by illwieckz** [comment]
What prefix to use? and why some cvars use `dot.naming.scheme` and others use `a_prefixedName`?

**Comment by slipher** [comment]
The dot scheme is a new one introduced in Daemon, but of course most of the old ones were never migrated... not convinced it's better as the dot naming is usually longer to type.

Use `r_` prefix I guess since all hardware workarounds are related to renderer AFAIK.

**Comment by hypov8** [comment]
something like r_ignore...
r_ignoreMemLimitation
r_ignoreNvidiaFix

**Comment by VReaperV** [comment]
Done in #1224.
