### ISSUE TITLE
Engine often fails to grab input on vid_restart or r_fullscreen toggling

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#365]
I experience this bug a lot were the game fails to grab input after `vid_restart`. The grab failure is easy to reproduce by putting the game window behind another unrelated window while the reloading is going on, waiting enough to make sure the whole reload process complete (and map is displayed again) before putting the game window on foreground.

Also, toggling fullscreen / windowed mode is likely to reproduce the bug, especially going from fullscreen to windowed mode.

Better a load a map first to reproduce the bug.

A `vid_restart` call while keeping the game in foreground usually grabs input again (but I'm afraid it may only be done on a TTY console in some case).

**Comment by illwieckz** [comment]
It looks like the bug also occurs when Alt-Tabbing from fullscreen: input is lost when returning to the game.

**Comment by illwieckz** [comment]
This bug is critical. Players quit the game in a middle of playing because of this. @slipher you seems to know a bit the input code, do you have any idea about that bug?

If we don't know how to fix it we better workaround it by calling `vid_restart` on Alt-Tab. Releasing something with such bug in it would be a disaster.

**Comment by bofh80** [comment]
Right, according to this : https://discourse.libsdl.org/t/problem-with-switching-between-full-screen-to-window-mode/24689

> You’ll need to use: SDL_SetWindowFullscreen(mWindow, 0); to get out of fullscreen mode, and then use: SDL_SetWindowSize(SDL_Window* window, int w, int h) to set the size of the screen. 

So it seems you need to tell SetWindowSize and it should start working properly. Note a comment from the bottom

> Calling SDL_SetWindowSize(SDL_Window* window, int w, int h) in the start of the next frame was the solution.

I had a look at adding the SetWindowSize, but i'm not sure how it relates to GLimp_StartDriverAndSetMode or GLimp_SetMode. Maybe you want the setwindowsize in one of those functions, and call it when the fullscreen switches back to windowed mode.

Best I could find, and it does seem quite relevant.

**Comment by illwieckz** [comment]
Related issues:

- https://github.com/DaemonEngine/Daemon/issues/234
- https://github.com/DaemonEngine/Daemon/issues/408
- https://github.com/Unvanquished/Unvanquished/issues/1136

@bofh80 interesting!

**Comment by illwieckz** [comment]
Fixed by DaemonEngine/Daemon#409.

**Comment by illwieckz** [comment]
I wonder if we can do improvements based on suggestion there: https://github.com/DaemonEngine/Daemon/issues/365#issuecomment-749806034.
