### ISSUE TITLE
notice or warning? logger.Notice("...WARNING: …") in sdl_glimp.cpp

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#371]
Notice or Warning?

https://github.com/DaemonEngine/Daemon/blob/6b94e2e890f893afdc55b7f70bd58cb39f3cafcd/src/engine/sys/sdl_glimp.cpp#L855-L871

**Comment by slipher** [comment]
How about `Warn` with red text, for an extra big warning (and remove the redundant WARNING from the message).

**Comment by VReaperV** [comment]
This does a Log::Warn() now instead.
