### ISSUE TITLE
Connecting to 0.51.1 server with 0.52.0 client shutdowns the game. Can we return to main screen instead?

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#372]
Connecting to 0.51.1 server with 0.52.0 client displays a popup telling this:

```
Warn: Error during error handling: CGame VM: Reader: Unread bytes at end of message
```

then the game quits. Can we return to main screen instead?

**Comment by illwieckz** [comment]
Note: I'm running with shared lib game (debug build).

**Comment by slipher** [comment]
`vm.cgame.type` gets set to 0 when you connect to a server because it is a cheat var.

**Comment by slipher** [comment]
This is basically working as intended (see #202). You shouldn't be able to bring your own cgame when connecting to a remote server (unless cheats are allowed).
