### ISSUE TITLE
Dynamic lights not removed on GeForce GTX 1070

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#386]
Whenever I fire one of the weapons with a muzzle flash (e.g. rifle, lasgun, mdriver), the light effect persists indefinitely, until the next time the weapon is fired, upon which it moves to the current location. There is the same issue with the lights produced on the impact of the pulse rifle and lucifer cannon projectiles, which similarly don't disappear until the next projectile hits.

The bug occurs alike with the 0.51 release and a 0.52 branch build. I haven't seen it before, so there may be a recently introduced driver bug.

The bug does not occur if I use the Intel integrated driver.

The bug does not occur with `r_dynamicLights 0`.

![image](https://user-images.githubusercontent.com/7809431/96421918-ff51b200-11bc-11eb-9de0-3246fac80c7a.png)
![image](https://user-images.githubusercontent.com/7809431/96421952-0973b080-11bd-11eb-887e-5c3f0ac36478.png)
![image](https://user-images.githubusercontent.com/7809431/96422052-27d9ac00-11bd-11eb-8210-850a0c05a0d4.png)

### System info
Windows 10

```
]/gfxinfo
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 1070 with Max-Q Design/PCIe/SSE2
GL_VERSION: 4.6.0 NVIDIA 452.06
GL_SHADING_LANGUAGE_VERSION: 4.60 NVIDIA
GL_MAX_VERTEX_UNIFORM_COMPONENTS 4096
^x0f0Using OpenGL 3.x context
Using GPU vertex skinning with max 233 bones in a single pass
```

> Driver Date: 8/12/2020
> Driver Version: 27.21.14.5206

**Comment by Stooberton** [comment]
This happens to me as well (Win10 w/ GTX 1080).

**Comment by slipher** [comment]
I can reproduce this on 0.52.0/sync on my *Radeon* hardware by setting `/r_dynamicLight 1`. This is a recent development, not in 0.51. But it suggests we have some problems with the code and not just driver bugs.

**Comment by illwieckz** [comment]
@Calinou got it in last RC game with nvidia as well.

**Comment by illwieckz** [comment]
Since be7229a it is expected `1` or `2` value for `r_dynamicLight` do the same (deprecated forward renderer now uses `-1`) I have noticed two test only testing for `2`, see #453.

**Comment by slipher** [comment]
> @slipher which driver and system did you used with your Radeon, the AMD one on Windows?
Yes

> Since be7229a it is expected 1 or 2 value for r_dynamicLight do the same (deprecated forward renderer now uses -1) I have noticed two test only testing for 2, see #453.

Maybe this can give us a hint about which part is going wrong...
