### ISSUE TITLE
Locally built engine seems not to be able to capture mouse

### ISSUE THREAD

**Issue by necessarily-equal** [DaemonEngine/Daemon#408]
When I start the game, if I keep it focused normally, I can play. But as soon as I select another window and switch back, it doesn't seem to catch the mouse again and I just see a fancy, useless cursor. Button press still shot or do whatever action is bound to the key, but I can't look around. I've seen the problem on Ubuntu 20.04 LTS, both with 0.52.0/sync, v0.51.1 and master branches.

may be related to #234.

**Comment by illwieckz** [comment]
Fixed by #409.
