### ISSUE TITLE
Status requests from unvanquished.net flagged as DRDoS

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#430]
On my server, I periodically get log lines of this form (from `SV_CheckDRDoS`):
```
Possible DRDoS attack to address 172.86.178.34, ignoring getinfo/getstatus connectionless packet
```

This is the IP of unvanquished.net. I suppose these requests can be coming from either the Wordpress plugin for unvanquished.net/servers, or the master servers.

**Comment by Gireen** [comment]
can you look how often you get getstatus requests and the port?
I get every 10 seconds 2 requests from unvanquished.net per server. 

I believe it is coming from mantis https://gitlab.com/Viech/Mantis

**Comment by slipher** [comment]
> I get every 10 seconds 2 requests from unvanquished.net per server.

I get the same pattern.

I can also make an additional request appear by refreshing unvanquished.net/servers.

**Comment by illwieckz** [comment]
From Mantis' [`unvquery.h`](https://gitlab.com/Viech/Mantis/-/blob/master/src/unvquery.h#L39-45):

```
// Minimum query periods for printActiveServers
#define PRINTACTIVESERVERS_LISTPERIOD   120
#define PRINTACTIVESERVERS_STATUSPERIOD 10

// Minimum query periods for checkPeekActivity
#define CHECKPEEKACTIVITY_LISTPERIOD    120
#define CHECKPEEKACTIVITY_STATUSPERIOD  10
```

First query is probably to build a list of active servers to answer `!list` commands, second query is the one done to tell users in channel there are players on a server.
