### ISSUE TITLE
Improve support to cvar namespaces

### ISSUE THREAD

**Issue by peoro** [DaemonEngine/Daemon#449]
I'd like to group cvars into "namespaces" more often. For instance, instead of using cvar called `g_doWarmup` and `g_warmup` I'd prefer to name them something like `game.warmup.enabled` and `game.warmup.time`. Daemon already uses a similar style for some cvars, like the logging ones, e.g. `logs.logLevel.sgame.default`.

It would be awesome if Daemon had better support for similar cvars. For instance, when tab-completing, it could list and autocomplete the namespaces without expanding them.

Would such a feature be welcome? We could even use a cvar to control this behavior, if people have different preferences.

**Comment by illwieckz** [comment]
Yes, I would like to see it as well. I also prefer the dot naming.

**Comment by slipher** [comment]
Fixed by #723.
