### ISSUE TITLE
Dynamic light fallback doesn't work

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#452]
For GL drivers lacking a certain extension, there is a fallback implementation of dynamic lights, which can be tested by replacing the line in sdl_glimp.cpp

    glConfig2.uniformBufferObjectAvailable = LOAD_EXTENSION_WITH_TEST( ExtFlag_CORE, ARB_uniform_buffer_object, r_arb_uniform_buffer_object->value );

with `glConfig2.uniformBufferObjectAvailable = false`.

However, this implementation produces no visible effect for me. It seems to be the same as setting `/r_dynamicLight 0`.

**Comment by illwieckz** [comment]
On Linux with Mesa drivers, it's expected to be possible to test the missing extension without modifying code, by using this environement variable:

```sh
export MESA_EXTENSION_OVERRIDE='-GL_ARB_uniform_buffer_object'
```

**Comment by slipher** [comment]
My suggestion to disable it by deleting a line was bad as it misses the part which sets shader defines. A right way to test with the extension disabled is `/r_arb_uniform_buffer_object 0`.

I found that in the 0.51 release, the fallback code path works correctly, but only if you have `r_dynamicLight 1` (the deprecated option). As of the latest 0.52/sync (including #453), the fallback code is broken even if you try to use the deprecated rendering path with  `/r_dynamicLight -1`, so there's a regression there.

**Comment by illwieckz** [comment]
My commit turning deprecated renderer as `-1` value was broken and then there was no way to re-enable the deprecated renderer.

This PR re-enables the deprecated renderer:

- https://github.com/DaemonEngine/Daemon/pull/1045

Once the deprecated renderer is working again and enabled, setting `r_arb_uniform_buffer_object` to `0`  makes a difference, the screen turn into black when there is a light in scene, meaning it uses an alternate code path but this code path is buggy.

If the fallback is only usable on the deprecated renderer, this is a good reason to keep the deprecated renderer as fallback itself.

**Comment by illwieckz** [comment]
> If the fallback is only usable on the deprecated renderer, this is a good reason to keep the deprecated renderer as a fallback itself.

That fallback is meant to be a fallback for the tiled lighting renderer, so having the option messing with the legacy lighting renderer is very suspicious. That fallback is part of the tiled lighting renderer.

The GLSL define used to select fallback code path when `ARB_uniform_buffer_object` is missing or disabled was inconsistent, but cleaning things up in #1182 doesnt help:

- https://github.com/DaemonEngine/Daemon/pull/1182

**Comment by VReaperV** [comment]
I propose just nuking that code-path. Virtually any hardware nowadays supports the extension, and ones that don't probably won't want to run with real-time lights enabled due to performance reasons.

**Comment by slipher** [comment]
Yeah nuke it

**Comment by VReaperV** [comment]
Fixed by NUKING the culprit with extreme prejudice in #1333.
