### ISSUE TITLE
Option to quit the game after a demo is played

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#487]
To make Dæmon-based games more benchmark friendly, it would be good to have a convenient way to shutdown the game at the end of a demo playing.

See https://github.com/Unvanquished/Unvanquished/issues/1440

**Comment by slipher** [comment]
Instead of only on demo ending, perhaps a command could be set on disconnecting and/or cgame termination, so that it would be more general purpose.
