### ISSUE TITLE
Nvidia fix likely broke GLSL 1.20 GPUs

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#490]
I wanted to try some optimization code and to test them on my old Thinkpad X61 Tablet on which Unvanquished was running at 0.52.0 time (slow but running), and then the engine reported failing to compile the `generic` shader:

```
Warn: Compile log:
0:44(20): error: bit-wise operations are forbidden in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
0:44(20): error: bit-wise operations are forbidden in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
```

The GPU is an Intel `GM965` one, that's one of the OpenGL 2.0 /  GLSL 1.20 ones.

This regression was probably introduced in #479 to fix #472.

On a side note: that's also why I asked for a comment telling why the code had to be written that way, because the motivation of this specific _shape_ of the code was not to implement something we want but to workaround something we don't want.

**Comment by slipher** [comment]
I did question whether those integer operations would be available on old versions, when I authored the fix. But I looked at some GLSL version history/release note things and couldn't find anything about integer operations, so I assumed it must have always been there ¯\_(ツ)_/¯

**Comment by illwieckz** [comment]
I was surprised as well that bit-wise operations were “modern” things… 😅

**Comment by illwieckz** [comment]
I was looking for a way to automate testing of the compatibility.

It looks like the required extension for bitwise operators in GLSL is [GL_EXT_gpu_shader4](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_gpu_shader4.txt).

By doing this (with 0.52.1 build):

```sh
MESA_GL_VERSION_OVERRIDE=2.1 \
MESA_GLSL_VERSION_OVERRIDE=120 \
MESA_EXTENSION_OVERRIDE='-GL_EXT_gpu_shader4' \
./daemon
```

I got this as expected:

```
0:44(20): error: bit-wise operations are forbidden in GLSL 1.20 (GLSL 1.30 or GLSL ES 3.00 required)
```

Doing that was not enough:

```sh
MESA_GL_VERSION_OVERRIDE=2.1 \
MESA_GLSL_VERSION_OVERRIDE=120 \
./daemon
```

This is probably because the extension is available anyway.

or:

```sh
MESA_EXTENSION_OVERRIDE='-GL_EXT_gpu_shader4' \
./daemon
```

This is probably because we blindly validate GL 3.1 core extension if that version is available.

So we have to properly set the versions and disable the extension.

Those options require a Mesa OpenGL driver, but one can use the Mesa software renderer, [even on Windows](https://github.com/pal1000/mesa-dist-win):

```sh
LIBGL_ALWAYS_SOFTWARE=1 \
MESA_EXTENSION_OVERRIDE='-GL_EXT_gpu_shader4' \
MESA_GL_VERSION_OVERRIDE=2.1 \
MESA_GLSL_VERSION_OVERRIDE=120 \
./daemon
```
