### ISSUE TITLE
libgeoip legal, licencing and privacy concerns

### ISSUE THREAD

**Issue by bmorel** [DaemonEngine/Daemon#492]
This issue is not per-se a technical one, even if I think technical answers can help. I am sorry that I can't find a better title for it.

My concerns are about a change in maxmind's geoip database licence, which makes it no longer FOSS.
This change only affects GeoLite2, not "legacy GeoLite" from my understanding. Naive answer could be "don't care, old DB is still under correct licence", but according to Maxmind, they changed licence to comply with some country's laws, which were made to protect people's privacy.

Currently, daemon build the libgeoip feature by default, it's opt-out at build time. There is no way for a client to disable the feature, same for server hosters.
The only use of it is to show a message like "$player connected from $country".

The questions it brings are:

* what does it means for server hosters to have this feature enabled (legally speaking)?
* should it be made it runtime-optional, through a variable which would be exposed in unvanquished's GUI (or any other game based on daemon, ofc) and a Cvar for hosters?
* should the option (either build-time, run-time or both) be opt-in or opt-out? Opt-in is the easier way to have people benefiting from it.
* what about the future? The DB is likely no longer maintained.
* is that feature worth the troubles at all?

**Comment by mboerwinkle** [comment]
The [GeoLite2 License](https://www.maxmind.com/en/geolite2/eula) does seem like a pain. Among other things, it requires constant maintenance ("cease use of and destroy (i) any old versions of the Services within thirty (30) days following the release of the updated GeoLite2 Databases"), though it is still based on CCA-ShareAlike.

> what about the future? The DB is likely no longer maintained.

GeoIP databases are not exceedingly reliable and require maintenance. I recommend against using an unmaintained GeoIP database.

> is that feature worth the troubles at all?

This feature is not very valuable to me relative to its complexity as an additional dependency. I suggest this feature could modified to use client locale information instead of GeoIP (possibly contingent on client opt-in/out).

Thanks,
Martin

**Comment by necessarily-equal** [comment]
For Linux, maybe we do rely on the GeoIP database provided by the distro? Chances are that a lot of the servers are Linux ones?

**Comment by bmorel** [comment]
Sure we can, and that's how it works for me, although I have disabled the feature since 1) it's not much useful and 2) the DB won't be updated anew, it's deprecated, un-maintained, and maybe it would only work for me because I'm on a Debian, which is well known for it's slowness to adopt changes, which leads to things staying around longer.

So, there is indeed the licencing problem, but there's also the problems about laws, since AIUI, in EU (GDPR) requires explicit consent to store informations about people, and I believe that IPs are included.
Daemon as, AFAIK, no feature to ask people if they want their country to be stored (since they are, in logs), and it's not required to function (proof is: the option can be disabled).

Even if they accept, users can also ask the service provider to remove the data, so by a simple principle of less risks and hassle, I disable that feature, but I wonder if it's a good idea to keep such an option enabled by default.

**Comment by illwieckz** [comment]
Speaking about doing country statistics, that can be done from outside the game with IP address even if the game does not know how to query GeoIP or other databases like that.

For example when I [did some stats in 2015]( https://forums.unvanquished.net/viewtopic.php?f=4&t=1854) (time flies!), I did used GeoIP but as an external tool, not relying to the in-game feature to produce that (it was about players on my server for 7 months):

[![2015 stat](https://dl.illwieckz.net/b/unvanquished/extra/stats-20150703-gg.illwieckz.net-7-months/20150703-013926.unvanquished-gg.illwieckz.net-7-months.countries.png)](https://dl.illwieckz.net/b/unvanquished/extra/stats-20150703-gg.illwieckz.net-7-months/20150703-013926.unvanquished-gg.illwieckz.net-7-months.countries.png)

Though, one thing that may be useful for GeoIP may not be user-related: we may display the country of the server in the in-game server list, and that's not personal data. [XQF](https://github.com/XQF/xqf) does this for example.

2018:

[![XQF](https://dl.illwieckz.net/b/xqf/shots/20180813-175656-000.xqf-country-flags.png)](https://dl.illwieckz.net/b/xqf/shots/20180813-175656-000.xqf-country-flags.png)

2021:

[![XQF](https://dl.illwieckz.net/b/xqf/shots/20210725-170953-000.xqf-country-flags.png)](https://dl.illwieckz.net/b/xqf/shots/20210725-170953-000.xqf-country-flags.png)

**Comment by Gireen** [comment]
There is no legal or privacy problem.
The few informations that daemon saves are necessary for running the game.

**Comment by bmorel** [comment]
the informations libgeoip provides are not necessary, otherwise it would not be an opt-out build option. But I honestly don't know which informations exactly daemonded stores, when linked with geoip. If the answer is none, then sure, it's nice. I was just bringing that potential problem, if there's none, it's all the better.

**Comment by illwieckz** [comment]
As slipher said on IRC:

> the problem is that the database is no longer updated

People doing stats can still correlate IP with geographic data like GeoIP or another provider using third party tools. Removing GeoIP would probably just remove the “someone connected from there” mention, which is likely wrong as the database is outdated.

Removing GeoIP would also remove one more dependency, and for something that has very low usage.

We may prefer offering the user the ability to chose his country in a list if he wants to advertise his country, that's still something that can be useful for social reasons (we may even display it in scoreboard).

At some point I wanted to display the country in server list, but that can be a server-provided cvar as well. Also it would move from us any conflict about territories being claimed by some or others (Israel/Palestine, Tibet/China/India, Hong-Kong/China, Donbass/Ukraine/Russia, `<insert others>`).

**Comment by illwieckz** [comment]
Also for server owners that like to know from where players connect to (this can be useful in multiple ways), maybe we can just implement a fully optional geoip query that just call the `geoiplookup` command line tool if exist, without us building anything about it.

**Comment by slipher** [comment]
The databases will be maintained until the end of May 2022, so we could leave it in for 0.53 and delete it only after that if we want.

**Comment by illwieckz** [comment]
I'm OK with that.

**Comment by slipher** [comment]
Actually, where is the GeoIP.dat file supposed to come from? Are users supposed to acquire it themselves? If so, we should remove the feature now since the databases would be available for only a short fraction of the release life.

**Comment by illwieckz** [comment]
It looks like it only reads it from libpath and, outside of Windows, build path.

What's weird is that we never distributed such GeoIP `.dat` file, but it is said the data is loaded while no file is read from hard drive, and it seems to work. Maybe the GeoIP library embed a snapshot of the database file? I don't know, but in all case, it looks like the `.dat` file is expected to be brought by the user himself if such user wants fresh data.

`$ ~/.local/share/unvanquished/base/daemon 2>&1 | grep -i GeoIP`:
```
Error Opening file /Unvanquished/daemon/external_deps/build-linux64-5/prefix/share/GeoIP/GeoIP.dat
Error Opening file /home/illwieckz/.local/share/unvanquished/base/GeoIP.dat
Error Opening file /Unvanquished/daemon/external_deps/build-linux64-5/prefix/share/GeoIP/GeoIPv6.dat
Error Opening file /home/illwieckz/.local/share/unvanquished/base/GeoIPv6.dat
Loaded GeoIP data: ^1IPv4 ^1IPv6
```

`$ strace --follow-forks ~/.local/share/unvanquished/base/daemon 2>&1 | grep -i GeoIP`:
```
[pid 392211] openat(AT_FDCWD, "/Unvanquished/daemon/external_deps/build-linux64-5/prefix/share/GeoIP/GeoIP.dat", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 392211] write(2, "Error Opening file /Unvanquished"..., 99Error Opening file /Unvanquished/daemon/external_deps/build-linux64-5/prefix/share/GeoIP/GeoIP.dat
[pid 392211] openat(AT_FDCWD, "/home/illwieckz/.local/share/unvanquished/base/GeoIP.dat", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 392211] write(2, "Error Opening file /home/illwiec"..., 76Error Opening file /home/illwieckz/.local/share/unvanquished/base/GeoIP.dat
[pid 392211] openat(AT_FDCWD, "/Unvanquished/daemon/external_deps/build-linux64-5/prefix/share/GeoIP/GeoIPv6.dat", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 392211] write(2, "Error Opening file /Unvanquished"..., 101Error Opening file /Unvanquished/daemon/external_deps/build-linux64-5/prefix/share/GeoIP/GeoIPv6.dat
[pid 392211] openat(AT_FDCWD, "/home/illwieckz/.local/share/unvanquished/base/GeoIPv6.dat", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 392211] write(2, "Error Opening file /home/illwiec"..., 78Error Opening file /home/illwieckz/.local/share/unvanquished/base/GeoIPv6.dat
[pid 392211] write(2, "Loaded GeoIP data: ^1IPv4 ^1IPv6", 32Loaded GeoIP data: ^1IPv4 ^1IPv6) = 32
[pid 392211] sendmsg(34, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\336\300\323\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=16}, {iov_base=NULL, iov_len=0}, {iov_base="\0", iov_len=1}, {iov_base="\n\0\0\0 \0\0\0Loaded GeoIP data: ^1IPv"..., iov_len=40}], msg_iovlen=4, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL <unfinished ...>
```

`daemon/src/engine/qcommon/net_ip.cpp`:
```c++
static GeoIP *NET_GeoIP_LoadData (int db)
{
	GeoIP *data = GeoIP_open_type (db, GEOIP_MEMORY_CACHE);

	if (data == nullptr)
	{
		if (db == GEOIP_COUNTRY_EDITION)
		{
			std::string dbPath = FS::Path::Build(FS::GetLibPath(), "GeoIP.dat");
			data = GeoIP_open (dbPath.c_str(), GEOIP_MEMORY_CACHE);
		}
		else if (db == GEOIP_COUNTRY_EDITION_V6)
		{
			std::string dbPath = FS::Path::Build(FS::GetLibPath(), "GeoIPv6.dat");
			data = GeoIP_open (dbPath.c_str(), GEOIP_MEMORY_CACHE);
		}
	}

	return data;
}
```

`geoip/geoip-api-c-1.6.12/libGeoIP/GeoIP.c`:
```c
GeoIP *GeoIP_open_type(int type, int flags) {
    GeoIP *gi;
    const char *filePath;
    if (type < 0 || type >= NUM_DB_TYPES) {
        printf("Invalid database type %d\n", type);
        return NULL;
    }
    _GeoIP_setup_dbfilename();
    filePath = GeoIPDBFileName[type];
    if (filePath == NULL) {
        printf("Invalid database type %d\n", type);
        return NULL;
    }
    gi = GeoIP_open(filePath, flags);

    if (gi) {
        /* make sure this is the requested database type */
        int database_type = gi->databaseType;
        if (database_type > 105) {
            database_type -= 105;
        }
        /*  type must match, but we accept org and asnum,
         *  since domain and *conf database have always the wrong type
         *  for historical reason. Maybe we fix it at some point.
         */
        if (database_type == type || database_type == GEOIP_ASNUM_EDITION ||
            database_type == GEOIP_ORG_EDITION) {
            return gi;
        }
        GeoIP_delete(gi);
    }

    return NULL;
}
```

`geoip/geoip-api-c-1.6.12/libGeoIP/GeoIP.c`:
```c
void _GeoIP_setup_dbfilename(void) {
    if (NULL == GeoIPDBFileName) {
        GeoIPDBFileName = malloc(sizeof(char *) * NUM_DB_TYPES);
        memset(GeoIPDBFileName, 0, sizeof(char *) * NUM_DB_TYPES);

        GeoIPDBFileName[GEOIP_COUNTRY_EDITION] =
            _GeoIP_full_path_to("GeoIP.dat");
[…]
        GeoIPDBFileName[GEOIP_COUNTRY_EDITION_V6] =
            _GeoIP_full_path_to("GeoIPv6.dat");
[…]
```

`geoip/geoip-api-c-1.6.12/libGeoIP/GeoIP.c`:
```c
char *_GeoIP_full_path_to(const char *file_name) {
    int len;
    char *path = malloc(sizeof(char) * 1024);

    if (GeoIP_custom_directory == NULL) {
#if !defined(_WIN32)
        memset(path, 0, sizeof(char) * 1024);
        snprintf(
            path, sizeof(char) * 1024 - 1, "%s/%s", GEOIPDATADIR, file_name);
#else
[…]
```

`geoip/libGeoIP/Makefile.am`:
```make
AM_CPPFLAGS = -DGEOIPDATADIR=\"$(pkgdatadir)\" -Wall
```

**Comment by bmorel** [comment]
> The databases will be maintained until the end of May 2022, so we could leave it in for 0.53 and delete it only after that if we want.

We're in april, almost may, and 0.53 is still not there. Is it really a good idea to ship a useless feature based on outdated database, which may have legal concerns, turned *on* by default?

**Comment by necessarily-equal** [comment]
Well well, ok, I'm ok with removing geoip if y'all want to remove it. I 
find the downsides a bit exagerated, but geoip isn't terribly useful 
either I guess.

**Comment by bmorel** [comment]
The downsides are about legals, which is going harsher and harsher as time passes by. Hosts have other things to do than to worry about EU or other country's regulation. Considering how little useful the data is, I think the stuff is just a bad idea with the current political world.
Ofc, hosts can still compile this out from their mods (that's what I do, better safe than sorry), but it adds an entry barrier.
