### ISSUE TITLE
When setting in_nograb to 1, input is not grabbed but pointer is hidden when focusing

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#496]
When setting in_nograb to 1, input is not grabbed but pointer is hidden, maybe that's unwanted?

Also, the pointer move still affects the camera.

Enabling `in_nograb` may also be useful when doing benchmark: in that specific use case, not hiding pointers and not being used to move the camera may be wanted.

**Comment by illwieckz** [comment]
> When setting in_nograb to 1, input is not grabbed but pointer is hidden, maybe that's unwanted?

After re-reading myself I had to reproduce to understand why I've said…

I mean the desktop pointer is hidden like if it was captured.

> Also, the pointer move still affects the camera.

The only thing `in_nograb` seems to do is to not recenter the pointer.

I don't know if there is a bug, but the behaviour is a bit puzzling.

With `in_nograb` enabled when the game is on the main menu, the main menu displays the in-game mouse pointer, so there is a continuity, when entering the window the desktop pointer disappears and the in game pointer appear, when leaving the window the in game pointer disappears and the desktop pointer reappears. But outside of a menu, in a loaded game level, when entering the window the mouse pointer disappears and will only reappear when leaving the windows again.

**Comment by slipher** [comment]
I assume this was fixed by 4e9095477beab0a310958b6513a9a16ef3b0bd4c.
