### ISSUE TITLE
engine crash when loading terminus map with grid lighting instead of light mapping

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#500]
I got an engine crash when loading the terminus map with grid lighting enabled instead of usual light mapping.

**Comment by slipher** [comment]
What's grid lighting?
How do you turn it on?
Can we delete it? :laughing:

**Comment by illwieckz** [comment]
> What's grid lighting?

The alternate lighting, usually used by non-map entities like player models.

At some point I would like to have an option to get it used by movers so the baked shadows don't move with them…

> How do you turn it on?

`r_vertexLighting 1` (yeah it's misnamed)

> Can we delete it?

It can be useful for some testing to be able to render the whole world with it, anyway we need this feature to be fully implemented for player models, buildables and other things like that.

The crash has probably a very stupid cause, because this code is used on every game when rendering players, buildables and weapons and then is known to work as expected.

**Comment by illwieckz** [comment]
Note: you can also show the light grid by doing:

`r_showLightGrid 1`

**Comment by illwieckz** [comment]
Also grid lighting may be used on some world surfaces when a map is compiled with a special option to not bake lightmaps on all surfaces (I forgot the name of that option). Our maps do not make use of this, but Wolf:ET for example did. This was a hack to reduce lightmap size if I'm right. This feature also currently work, so the bug may really be stupid.

**Comment by DolceTriade** [comment]
Is this still an issue? I can repro?

**Comment by slipher** [comment]
#653 fixes it.

Sometimes I had to delete the glsl cache directory to repro.

Daemon starting crashing after e4324793. This is because it no longer set up the uniformFirewall pointer for permutations that are supposed to be unused. Before that, it would go ahead and use the uninitialized shader program (from glCreateProgram).

c5c18ce4 is the source of the issue, disabling building the shader when r_vertexLighting is on.
