### ISSUE TITLE
Make in_nograb and in_mouse temporary cvars?

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#501]
For stuff like benchmark it may be useful to enable `in_nograb` (disable mouse pointer grab), but then, the next legit game would not grab the pointer. By setting `in_nograb` temporary benchmarks may disable grabbing without breaking the next game.

**Comment by illwieckz** [comment]
Same concern for `in_mouse`. Disabling `in_mouse` does not prevent to use the menu anyway.

**Comment by slipher** [comment]
This is no longer needed since we stopped auto-archiving cvars on `/cvarname value`. So stuff is only archived if you did it on purpose.
