### ISSUE TITLE
Renderer breakage on resolution change

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#55]
I've been getting renderer issues on the `for-0.51.0` branch when I change resolutions. I have a Radeon R7 200 on Windows 7. Usually I switch between a windowed configuration which sets `"r_mode -1; r_customwidth 900; r_customheight 700; r_fullscreen 0;vid_restart"` and a full-screen which sets `"r_customwidth 1920; r_customheight 1080; r_fullscreen 1; vid_restart"`. 

These work fine on a client compiled some time after 0.50, but one or the other of the resolutions is usually broken on the 0.51 branch. Usually the windowed one is the one that has distortion and a strange perspective. This is what it looks like in third-person mode:
![unvanquished_2017-11-13_050420_000](https://user-images.githubusercontent.com/7809431/32843561-f3479a8e-c9d4-11e7-8ce1-2d26aa8c0b19.jpg)

But I also got this situation, where windowed was normal, but full screen looks like this:
![unvanquished_2017-11-15_064852_000](https://user-images.githubusercontent.com/7809431/32843598-039bc892-c9d5-11e7-8451-3de13d02e64c.png)

**Comment by illwieckz** [comment]
Ans when returning back to the former resolution, some stuff still uses the larger resolution (the ssao filter I think).

**Comment by slipher** [comment]
Fixed with #105.
