### ISSUE TITLE
give trace_t coordinates of the blocking point

### ISSUE THREAD

**Issue by bmorel** [DaemonEngine/Daemon#560]
Currently, `trace_t` structure does not gives info about where the collision happened. It only gives the blocking entity's number, and a special number when it is geometry.
When it is a physical entity, it is possible to get back ways to avoid or to aim the blocker, but not when it's geometry (aka map).

This would mostly be useful to me to make bots in unvanquished able to combine computer-vision (traces) with navmeshes to find their paths, but it might have other uses too.

**Comment by necessarily-equal** [comment]
Actually thinking about it, you can do something like:

```c++
glm::vec3 collision = start + tr.fraction * (end - start);
```

I think this should give the calling function all the info it needs
