### ISSUE TITLE
GCC 11.2.0 on Linux: static variable declaration and affectation must be done separately.

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#566]
Initial title: _GCC 11.2.0 on Linux: affectation written before usage in source is done after usage in compiled code_

I noticed that this:

```c++
	static glConfiguration bestConfiguration = bestValidatedConfiguration;

	const char* bestProfileName = GLimp_getProfileName( bestConfiguration.profile );

	logger.Notice( "Best context: %d-bit OpenGL %d.%d %s",
		bestConfiguration.colorBits,
		bestConfiguration.major,
		bestConfiguration.minor,
		bestProfileName );
```

Does not print the same thing as:

```c++
	static glConfiguration bestConfiguration = bestValidatedConfiguration;

	const char* bestValidatedProfileName = GLimp_getProfileName( bestValidatedConfiguration.profile );

	logger.Notice( "Best context: %d-bit OpenGL %d.%d %s",
		bestValidatedConfiguration.colorBits,
		bestValidatedConfiguration.major,
		bestValidatedConfiguration.minor,
		bestValidatedProfileName );
```

In first case the logger prints the values from `bestConfiguration` _before_ it is overwritten by `bestValidatedConfiguration`, so it looks like in compiled code the affectation is done after the logger is called instead of being done before.

**Comment by slipher** [comment]
A function-local static variable is only initialized the first time the code is executed. So the value may be different on the 2nd or subsequent calls.

**Comment by illwieckz** [comment]
Does it mean I have to do:

```c++
static glConfiguration bestConfiguration;
bestConfiguration = bestValidatedConfiguration;
```

Instead?

**Comment by slipher** [comment]
Maybe? I have no context for what you're trying to do.

**Comment by illwieckz** [comment]
OK, splitting the lines fixes the issue on my end.

What I wanted to do is to set `bestConfiguration` static so I can compare `bestValidatedConfiguration` with previous `bestConfiguration` before copying `bestValidatedConfiguration` to `bestConfiguration`.

Now I understand that if I do the affectation on the declaration line the affectation would not be done on every function call but only once at first.
