### ISSUE TITLE
cvar description printing is super complicated and misleading

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#592]
Instead of building the printed line at printing time, it is built while doing this or that action.

It means for example the actual default value is not printed, but is printed after a reset:

```
/sv_master1 
"sv_master1" - text - address of a master server - default: "master.unvanquished.net"
/reset sv_master1 
/sv_master1 
"sv_master1" - "master.unvanquished.net" - text - address of a master server - default: "master.unvanquished.net" 
```

**Comment by slipher** [comment]
> the actual default value is not printed

The default value is always printed - `default: ` appears in both lines. The current value is not printed if it is equal to the default.

**Comment by illwieckz** [comment]
> The current value is not printed if it is equal to the default.

If you reset the cvar, it is printed even if it's equal to the default. Also it's hard to know if the current value is empty string or not (the lack of `""` only tells).

**Comment by slipher** [comment]
I always thought it was a feature to omit the value if it was no changed, but looking at the code it appears to be an accidental bug. I have a patch to fix that which I will put here soon.

**Comment by slipher** [comment]
#594
