### ISSUE TITLE
Windowed mode doesn't have window decorations on GNOME Wayland

### ISSUE THREAD

**Issue by necessarily-equal** [DaemonEngine/Daemon#633]
SDL2.0.22 and later have `SDL_HINT_VIDEO_WAYLAND_PREFER_LIBDECOR` so this is probably the way.

**Comment by necessarily-equal** [comment]
It can look like that:

![Screenshot from 2022-06-23 16-25-23](https://user-images.githubusercontent.com/59283660/175324381-1f39f82e-d069-411d-a0e5-04ecd865ef22.png)

I've thought a bit about it, and to be honest, I don't see a fundamental problem in this situation. I mean, what do you need the window for, a close button? Do we really need a close button? Alt-F4 works, the "quit game" button works. Not sure we need more.

* in KDE, you can close it from the bottom app list.
* in GNOME, you can close it from the overview.
* in Sway, you never have a close button anyway. I think other window manager would either rely on key binds to manipulate windows or draw their own decorations anyway.

The only problem might be that people aren't too used to it.

**Comment by illwieckz** [comment]
@slipher yes
@necessarily-equal the window decoration may be useful to move the window (on the screen, across screens).

**Comment by necessarily-equal** [comment]
SDL 2.0.22 brings this feature, and we have by default a working window decoration.

![image](https://user-images.githubusercontent.com/59283660/177019759-e63d669b-0dc8-4fed-b233-4b16ee1742a5.png)

It works well with `/r_noBorder` too, so there isn't anything to do here, except to use a recent SDL.
