### ISSUE TITLE
[Idea] Made beacons last longer (to make them more usefull)

### ISSUE THREAD

**Issue by superdupont-fr** [DaemonEngine/Daemon#642]
Hi!

The beacons appears for only 3 or 5 seconds, that is too short.
The time to almost understand where is it, and it lost.

Also, a path on ground (with jump possible?) to the nearest beacon should be show for Aliens, and Humans with helmet.

Humans bots should also put beacons, when they saw Aliens buildings for example.

When the building disappear, the beacon should too.
For beacons for defend, attack... I think 30 seconds should be enough.

**Comment by illwieckz** [comment]
This looks to be an issue for https://github.com/Unvanquished/Unvanquished/issues

**Comment by necessarily-equal** [comment]
Ideally we would have some lifetime management for beacons because even when "Defend" used to last 10s I often came for nothing because it was too late already

**Comment by bmorel** [comment]
Also: https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/122
