### ISSUE TITLE
VFS case sensitivity

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#65]
It looks like VFS case sensitive while loading dpkdir, but case insensitive while loading dpk. Historic behavior for pk3 seems to be case insensitive, do pk3dir/dpkdir have to be case insensitive too?

We can also decide to keep the case sensitivity behavior of pk3dir/dpkdir to force mapper to fixes their names. ( ͡° ͜ʖ ͡°)

We can also decide that pk3 zip is case insensitive because of legacy stuff but dpk is sensitive for newer stuff (has to be implemented) and in this case there is no big need to take care of pk3dir case insensitivity since it's stupid to do legacy pk3dir when you can do a clean and modern dpkdir yourself.

**Comment by DolceTriade** [comment]
I think this is a result of Linux file systems being case sensitive while we use case insensitive compare functions for our dpks.

**Comment by Viech** [comment]
I don't have a strong opinion on this. As long as old pk3 still work I'm leaning towards case-sensitivity, even though if that feature is actually used it means that mappers can't unpack dpk under windows without file name conflicts.

**Comment by slipher** [comment]
How about case sensitivity, but also it's an error if you have two files that are case-insensitively equal?

**Comment by Viech** [comment]
That sounds good, because it allows case-sensitive external tools to process maps and config files, while keeping compatibility with unpacking under Windows.

**Comment by slipher** [comment]
Fixed by #1315.
