### ISSUE TITLE
Empty or incomplete server list when using French Free Mobile and Bouygues Telecom Internet providers (LTE mobile broadband)

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#654]
It looks like there was no dedicated issue, here is a first attempt to workaround the problem:

- https://github.com/DaemonEngine/Daemon/pull/283

Free Mobile is a French Internet Provider (mobile broadband), it is very used as it is one of the only 4 mobile broadband providers for France.

When an user is connected to Internet through this kind of connection (for example sharing Internet with his phone), the game don't get answers from queried servers. It's possible the servers don't receive the queries to begin with.

It appears that waiting a bit between each server query works around the issue (hence the #283 attempt).

Among people who experience the problem are:

- @illwieckz
- @bmorel
- @necessarily-equal
- @superdupont-fr
- `err404` (chat user)
- `BL0CKY_DUDE` (chat user)

The current workaround is to use https://unvanquished.net/servers/ if `unv://` protocol integration is working.

I tag this issue as `Enhancement` and not as `Bug` because that's likely not a bug in our code, but a problem in provider's infrastructure. Though, it would be useful if our engine was more resilient to providers with network issues.

**Comment by illwieckz** [comment]
On a side note, a new implementation of server querying may also want to take care of that other issue:

- https://github.com/DaemonEngine/Daemon/issues/284

**Comment by necessarily-equal** [comment]
the duplicate https://github.com/DaemonEngine/Daemon/issues/654 has some screenshots

**Comment by superdupont-fr** [comment]
I almost never use shared connexion. But, I can test this case if needed. (since you added me in the list :D )

**Comment by illwieckz** [comment]
@bmorel reports the same issue happens with another French Mobile Internet provider: Bouygues Telecom.

**Comment by slipher** [comment]
This is nothing out of the ordinary... some servers missing during a client server list refresh has always happened since Tremulous. The client just sends a serverinfo request and the server doesn't appear if the packet gets lost or the response takes too long. If you guys have not seen this before now, you must have been blessed with unusually reliable ISPs.

**Comment by illwieckz** [comment]
But when this bugs happen, having at least one sever listed in the list is the exception, otherwise none are listed.

**Comment by bmorel** [comment]
FWIW I think the problem I had yesterday was a temporary problem, as I did not had it before, and it seems it's gone this morning.
