### ISSUE TITLE
branch name for the “next” version?

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#665]
Now that we have a nightly build server, we may rethink the naming of the “next” version branch, for when we have things that cannot be merged in master (though we may avoid it the most possible because it's painful).

Until now we named them like `0.53.0/sync`, but that's not really predictable by a simple script. Why not simply call it `next/sync`?

Once a new version is released, any next branch will be called “next”.

We don't expect to have more than one “next” branch anyway.

What do you think about it?

**Comment by DolceTriade** [comment]
next-sync makes sense and it can be deleted and recreated after every release?

**Comment by illwieckz** [comment]
Yes that's the idea, delete it after every release and recreate it when there is a need.

Note: the slash in `/sync` is on purpose as our CI relies on `git-checkout-modules` to fetch any submodule with the same branch of the PR if the branch name ends with `/sync` has a convention.

**Comment by slipher** [comment]
This has potential for confusion. If there is a pull request sitting with the `next` target branch, then it won't be obvious when the release had passed that you should consider retargeting it to master. I prefer explicitly numbered branches.

**Comment by slipher** [comment]
Also when looking at merge commits in the history I would rather see "merged 0.53.0 into master" and vice versa, than just "next".

**Comment by necessarily-equal** [comment]
In the case of nightly, it only uses `master`. In the case of the testing servers, the `/experimental` servers are hardcoded to use `0.53.0/sync`. It's not really a big deal to change that though.

**Comment by VReaperV** [comment]
Is this still relevant? It seems we have kept using branch names like `for-0.56.0/sync`.

**Comment by illwieckz** [comment]
Anyway the question was for having a generic branch name not having a version.
