### ISSUE TITLE
Raise entity limit for 0.54 release

### ISSUE THREAD

**Issue by cu-kai** [DaemonEngine/Daemon#719]
Mentioning @DolceTriade for this one. Recently some PvE maps have caused crashes on several servers due to low entity limit (1024). This should ideally be raised to 2048 or 4096.

TODO also: investigate performance with high numbers of entities?

**Comment by cu-kai** [comment]
@illwieckz if I am not mistaken, the work for this begins here: 
https://github.com/DaemonEngine/Daemon/blob/master/src/engine/qcommon/q_shared.h#L1648

However, changing this alone is not enough in my very limited testing.

**Comment by necessarily-equal** [comment]
Closed by https://github.com/DaemonEngine/Daemon/pull/764
