### ISSUE TITLE
Build on Ubuntu could not find Nettle.

### ISSUE THREAD

**Issue by karriszou** [DaemonEngine/Daemon#722]
I build Daemon on Ubuntu 20.04LTS, the following error occurred:

**CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Nettle (missing: NETTLE_LIBRARY HOGWEED_LIBRARY
  NETTLE_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindNettle.cmake:11 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:630 (find_package)**

**-- Configuring incomplete, errors occurred!**

On my system, there is libnettle7 is installed, no libnettle package available, can someone help me to build?
Thanks a lot !

**Comment by DolceTriade** [comment]
`sudo apt install nettle-dev`

**Comment by illwieckz** [comment]
You may also find more details there: https://wiki.unvanquished.net/wiki/Compiling_the_source#Debian.2FUbuntu

**Comment by karriszou** [comment]
> `sudo apt install nettle-dev`

thanks you help! it's my stupid, I thought all packages had a lib prefix...

**Comment by karriszou** [comment]
> You may also find more details there: https://wiki.unvanquished.net/wiki/Compiling_the_source#Debian.2FUbuntu
> 
> (Except you may ignore debian packaging and use the cmake instructions from the README like you already do)

Thanks for your replay! the instruction is very detail, I regret finding Daemon engine too late and salute for your great work!

In addition, the authors of ET:XreaL is seems to working on RBDoom3BFG, what do you think and do you have an idea for upgrading the renderer to doom3's renderer?

Have a good day!
