### ISSUE TITLE
pure white line artifact on edges

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#76]
This is a weird behavior we can see on some different use cases:

- lines because two edges are rendered very near even if they are on different depth, note that in some condition (and angle) the lines can be red or other colors:

[![white edge artifact](https://dl.illwieckz.net/b/unvanquished/bugs/white-edge-artifact/unvanquished_2017-09-28_002547_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/white-edge-artifact/unvanquished_2017-09-28_002547_000.jpg)
[![white edge artifact](https://dl.illwieckz.net/b/unvanquished/bugs/white-edge-artifact/unvanquished_2017-10-18_233510_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/white-edge-artifact/unvanquished_2017-10-18_233510_000.jpg)

- lines on surfaces junction:

[![white edge artifact](https://dl.illwieckz.net/b/unvanquished/bugs/white-edge-artifact/unvanquished_2018-02-06_231004_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/white-edge-artifact/unvanquished_2018-02-06_231004_000.jpg)
[![white edge artifact](https://dl.illwieckz.net/b/unvanquished/bugs/white-edge-artifact/unvanquished_2018-02-11_233456_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/white-edge-artifact/unvanquished_2018-02-11_233456_000.jpg)

**Comment by illwieckz** [comment]
Disabling deluxeMaps makes that bug disappear.

**Comment by illwieckz** [comment]
A good information to know is that lower resolution lightmaps do not trigger the bug. I discovered this after having rebuild lower-res lightmaps from vega and chasm.

**Comment by Viech** [comment]
Have you maybe compressed the deluxemaps? They should be as sensitive as lightmaps towards compression, if not more, since they are not to be understood as a visual image but as a vector map that stores the direction of incoming light. In particular deluxemaps are used for both normal mapping and specular reflections, and it could be that corrupted deluxe vectors give you a sort of specular super-reflection that isn't quite based on your view angle anymore.

**Comment by illwieckz** [comment]
I always use lossless compression myself, by the way it's possible the jota map above was using lossy webp from lightmap (hence deluxemaps), I know and I verified that even high quality lossy webp are _wrong_ for lightmaps, and I'm almost sure I've already seen lossy webp lightmaps in some Matth's packages. For other maps like vega or thunder, no one did the lossy mistake…

**Comment by illwieckz** [comment]
the issue on jota seems to have nothing to do with the one on parpax, the one on parpax is highly related to https://github.com/UnvanquishedAssets/map-station15_src.dpkdir/issues/3 which is a lightmap issue related to specularity.

**Comment by illwieckz** [comment]
The issue on jota map seems to be the conjunction of two things:

- lossy lightmaps, making unseen part of lightmaps spilling out.
- #3, making some part of lightmaps (usually unseen) pure white.

Once deluxe mapping is disabled, we see the lightmap spilling out but with colors that looks legit, not pure white. That's the exact same behavior described in https://github.com/UnvanquishedAssets/map-station15_src.dpkdir/issues/3.

The problem of this map shipping lossy lightmaps is a map issue that is unrelated to the engine.

**Comment by illwieckz** [comment]
This is confirmed that jota issue was the collision of two bugs, lightmaps spilling out (probably due to lossy webp compression) that would not be fixable, and the issue described in #299, fixed in #306 which makes those wrong lightmap going crazy.

Now that lightmap going crazy is fixed, we can still see lightmaps spilling out in jota, but at least they have the colors we expect. Since fixing lightmap is out of topic, this issue is definitely a duplicate of #299 (initially UnvanquishedAssets/map-station15_src.dpkdir#3).

**Comment by slipher** [comment]
Wow, nice job figuring that out.

**Comment by illwieckz** [comment]
We had bugs layered above bugs. :grin:
