### ISSUE TITLE
missing cvar to disable deluxeMap rendering

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#79]
There is currently no cvar to disable deluxeMap rendering. Being able to switch deluxeMap on and off is useful to check if a bug is related to deluxeMap or not.

**Comment by Viech** [comment]
To my knowledge "disabling" deluxemaps is equivalent to disabling both normal mapping and specular mapping. (Disabling in the sense that these two effects should be exactly the code that makes use of deluxemaps, and neither can work without them.)

**Comment by illwieckz** [comment]
Using both `r_normalMapping 0` and `r_specularScale 0 (I haven't seen a switch to disable it) does not workaround the issues seen in #68 and #76. But disabling deluxeMap in code does. Is there a way to be sure to disable specular mapping?

**Comment by Viech** [comment]
Hmm, now that I think about it it may be that `r_normalmapping` controls both normal mapping and specular mapping. Technically, specular mapping could use only deluxe maps but that would give weird flat reflections, so I think this was never implemented.

**Comment by illwieckz** [comment]
So why the bugs are there when I set `r_normalMapping` to `0` but not when I disable deluxeMap stuff in code?

**Comment by illwieckz** [comment]
See #188 for a `r_deluxeMapping` implementation.

**Comment by VReaperV** [comment]
Fixed by #118. The check for deluxe maps to enable normal, specular and physical mapping is at https://github.com/DaemonEngine/Daemon/blob/9e51d49aa973c084358e0a78116955df5abf0187/src/engine/renderer/tr_shade.cpp#L141
