### ISSUE TITLE
Dynamic light blockiness (tile edges visible)

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#791]
Using the tiled renderer, the area covered by a dynamic light can have visible, blocky edges. The issue can be observed by firing a single pulse rifle shot. Here's a screenshot by illwieckz: [![light blockiness](https://dl.illwieckz.net/b/unvanquished/bugs/light-blockiness/unvanquished_2023-01-19_145745_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/light-blockiness/unvanquished_2023-01-19_145745_000.jpg)

The tiled lighting works in two phases:
1. In the `lighttile` shader, compute the set of lights which is believed to affect each tile. The assumption is that tiles sufficiently far away should be close enough to completely dark not to matter. 
2. When rendering a surface, apply each light in the list for the relevant tile.

It seems that the assumption in (1) is wrong and some of the tiles considered to be not affected actually would have had a significant amount of light. Two obvious approaches to fix this:
(a) Change the calculation of which tiles are affected to rule in more tiles
(b) Change the falloff curve of brightness vs. distance so that the brightness is actually close enough to 0 at the edges

**Comment by DolceTriade** [comment]
Would be really amazing to fix this!
