### ISSUE TITLE
R_LoadDDSImage: unsupported FOURCC 0x33545844

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#82]
Dæmon fails to load some Xonotic textures, here is an example:

```
Warn: R_LoadDDSImage: unsupported FOURCC 0x33545844, "dds/models/desertfactory/textures/misc/grass01.dds" 
```

You can find the file there: [grass01.dds](http://dl.illwieckz.net/b/daemon/bugs/dds-invalid-fourcc/grass01.dds)

Note that `crunch` is able to convert this `dds` file back to `tga` without complaining so perhaps we can rely on `crnlib` for `dds` files too?

**Comment by illwieckz** [comment]
`FOURCC 0x33545844` is `DXT3` which uses a format very close to DXT5 (they said [here](https://www.fsdeveloper.com/wiki/index.php?title=DXT_compression_explained) only transparency differs).

**Comment by illwieckz** [comment]
I just did that and it seems to work:

```diff
diff --git a/src/engine/renderer/tr_image_dds.cpp b/src/engine/renderer/tr_image_dds.cpp
index 60f836484..35011d9aa 100644
--- a/src/engine/renderer/tr_image_dds.cpp
+++ b/src/engine/renderer/tr_image_dds.cpp
@@ -277,6 +277,11 @@ void R_LoadDDSImageData( void *pImageData, const char *name, byte **data,
                        blockSize = 8;
                        break;
 
+               case FOURCC_DXT3:
+                       *bits |= IF_BC3;
+                       blockSize = 16;
+                       break;
+
                case FOURCC_DXT5:
                        *bits |= IF_BC3;
                        blockSize = 16;
```

**Comment by slipher** [comment]
I'm coming from a position of total ignorance here, but how can you expect it to be correct if you render a texture format with exactly the same code as a different format? Also, I don't see DXT3 on the list of formats in the crunch README.

**Comment by slipher** [comment]
Never mind about DXT3, I see it is actually discussed further down in the document.

**Comment by illwieckz** [comment]
If I'm right we never render the pixmap ourselves, we just stream the pixels to the GPU.

That's precisely the purpose of _DDS_ or _crn_: they are compressed formats made to be uncompressed and rendered by the GPU so you save a lot of time since 1. you don't decompress them on CPU (you save CPU time), 2. you send them to GPU as-is (you save loading time thanks to bandwith saving).

So if I'm right, the only thing we have to know is to somewhat unpack the container, basically telling bitness and things like that. It looks like DXT3 and DXT5 stores information on the same data structure, one part just not having the same meaning.

For what I've seen, both DXT3 and DXT5 are using the same _bits per pixel_ count, even if the alpha ones are not groked the same way.

So, yes, that's a good question and that's the purpose of that talk: _is it enough_? Perhaps yes, I haven't seen any issue while testing but there is a high probability I miss something since there is still many things unsupported in Dæmon so we can't compare to reference yet (see my comment [there](https://github.com/DaemonEngine/Daemon/pull/84#issuecomment-372415645)).

**Comment by illwieckz** [comment]
Hence I would very appreciate having a comment from some engine wizard like @gimhael, @cmf028, @kangz, or @Amanieu on that topic…

**Comment by gimhael** [comment]
DTX3 (BC2) and DXT5 (BC3) use different alpha encoding, though both use 4 bit per pixel, so just declaring DXT3 textures as DXT5 will result in garbled alpha values. The pull request above (untested) should handle it correctly.
