### ISSUE TITLE
Intel UHD: heavily distorted and flickering textures on world surfaces

### ISSUE THREAD

**Issue by ghost** [DaemonEngine/Daemon#909]
I have that kind of flickering on various maps, at extremely precise point.
I know it can be the map itself, but it could be just another case of [this](https://github.com/Unvanquished/Unvanquished/issues/2500) too, which might help finding out the problem.

ATCSZ alpha:

![2023-05-31_004](https://github.com/DaemonEngine/Daemon/assets/1316300/77326335-eceb-43b2-bffd-1f1209242b5f)

I'll try to think about updating this when I find new spots, I have feeling this happens more often than in the past. Maybe I'm wrong.

**Comment by cu-kai** [comment]
I can reproduce this on Intel UHD 620 graphics on linux on a number of maps. I believe one of the ATCS variants had this bug, but it wasn't atcs zone alpha.

**Comment by cu-kai** [comment]
I am seeing this with a `00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)` (CPU is an `i5-8350U`)

**Comment by illwieckz** [comment]
- ✅️: no bug
- ❌️: bug
- ❔️: not tested

Chip|Windows|Linux|Tester|Details
--|--|--|--|--
UHD 630 (CFL GT2),<br/>CoffeeLake S|❔️|❌️|bmorel|Linux, driver 20.3.5
UHD 620 rev 07,<br/>i5-8350U, 8th gen,<br/>Kaby Lake R|❔️|❌️|cu-kai|Linux

**Comment by slipher** [comment]
I [reproduced](https://github.com/DaemonEngine/Daemon/issues/949#issuecomment-1793576281) the bug on map rush-station on my UHD 630 on Windows.

**Comment by cu-kai** [comment]
On Windows 11 23H2 (build 22631.2428), Intel UHD 620, driver 30.0.101.1122 I can reproduce the rush-station bug easily and see the same sort of distortion.

**Comment by illwieckz** [comment]
Do you also reproduce it with stock thunder map on `-964 -250 70 15 23` position like in:

- https://github.com/Unvanquished/Unvanquished/issues/2500#issuecomment-1591861058

If yes it would be easier to give instructions to driver developers to reproduce the issues.

On my end I do this to open the map and set the viewpos in one go:

`daemon +devmap thunder +delay 200f setviewpos -964 -250 70 15 23`

**Comment by cu-kai** [comment]
I had to look a little to the left of those coordinates, but I can reproduce this one too.

**Comment by illwieckz** [comment]
Thanks.

Can you give exact coordinates that reproduce the issue on your end, with a screenshot for those exact coordinates?

I'll use them in a report as references.

**Comment by cu-kai** [comment]
Here is the screenshot, viewpos is echoed in the top left.

`-964 -250 70 35 22`

![unvanquished_2023-11-29_151324_000](https://github.com/DaemonEngine/Daemon/assets/13281185/5d3249a7-1808-4f8a-a267-971c281eac9b)

**Comment by illwieckz** [comment]
Thanks a lot!

**Comment by illwieckz** [comment]
I reproduced it with an HD 520, which looks like to be from the UHD generation but without a U in the name.

**Comment by illwieckz** [comment]
But on Mesa side:

- https://gitlab.freedesktop.org/mesa/mesa/-/issues/10224

**Comment by bmorel** [comment]
It is weird, as, I insist, the number of those increased greatly in the current release. I noticed this (long) before updating debian, and I don't remember kernel update (I need to do some things manually in my setup after those so I tend to notice them).

So, maybe there is a bug in drivers, but I'd be surprised if it's *only* driver related.
