### ISSUE TITLE
Debug draw interface is broken

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#924]
I inserted a simple test for the bot debug drawing facility at the beginning of `G_RunFrame`:

```
	Cvar::SetValue("r_debugSurface", "1");
	DebugDrawQuake dd;
	dd.init();
	dd.begin(DU_DRAW_TRIS);
	dd.vertex(500, 500, 600, -1);
	dd.vertex(600, 500, 500, -1);
	dd.vertex(500, 600, 500, -1);

	dd.vertex(-500, 500, -600, -1);
	dd.vertex(-600, 500, -500, -1);
	dd.vertex(-500, 600, -500, -1);
	dd.end();
	dd.sendCommands();
```

There should be one triangle around (500, 500, 500) and one around (-500, -500, 500), taking into account the swapped y/z coordinates. However most of the time, the triangles are drawn in some incorrect way, with triangles that use some verts from both sides. Tested on map Pushcannon:
![unvanquished_2023-08-21_115331_000](https://github.com/DaemonEngine/Daemon/assets/7809431/b56766df-7f5b-413f-8ea2-194985bac845)

The triangles that are actually drawn changes every now and then, on the order of one minute. A similar behavior can be seen with `navedit`, where triangles frequently appear and disappear.

## Workaround
I have tried this workaround with both Nvidia and Intel graphics. The bug can be avoided by setting these cvars together:
- `r_arb_map_buffer_range 0`
- `r_arb_buffer_storage 0`

**Comment by illwieckz** [comment]
Ah, nice find! Narrowing down such bug is good!
