### ISSUE TITLE
Lag compensation, client-side prediction?

### ISSUE THREAD

**Issue by VinnyVicious** [DaemonEngine/Daemon#933]
Are those features available in Daemon? How can they be enabled on a game server?

**Comment by DolceTriade** [comment]
unlagged is enabled by default. I don't think we allow any tuning from cvars, you'll have to modify the code.

If you want to disable it, g_unlagged = 0 for serverside and cg_unlagged = 0 for client side

**Comment by slipher** [comment]
To be clear, these features are not part of Daemon but may be implemented in the game logic.
- Lag compensation: G_UnlaggedOn() in https://github.com/Unvanquished/Unvanquished/blob/master/src/sgame/sg_active.cpp
- Client-side prediction: https://github.com/Unvanquished/Unvanquished/blob/master/src/cgame/cg_predict.cpp

**Comment by VinnyVicious** [comment]
Thank you for the clarification!
