### ISSUE TITLE
Intel UHD: station15 waterfall confetti rendering bug

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#949]
Graphics: Intel UHD Graphics 630
Does not happen with Nvidia.
The bug is present in 0.54.0 and master.
I thought it might be something to do with light tiles due to apparent rectangular tiles which seem to have a fixed size in pixels, but the bug still happens with dynamic lights off so no.
![unvanquished_2023-10-30_161833_000](https://github.com/DaemonEngine/Daemon/assets/7809431/3c3ce786-ca3b-448e-a01d-3451cb7e8512)

**Comment by slipher** [comment]
Fun fact: the bug goes away when navedit is enabled

**Comment by cu-kai** [comment]
I don't see this issue on AMD.

**Comment by illwieckz** [comment]
I never seen this is issue with any of GPU/driver configurations I tested in the past 3 years.

Hint: I don't own any Intel UHD hardware. 😅️

What a _beautiful_ bug anyway. 😎️🎉️

**Comment by cu-kai** [comment]
Could this be related to the other intel-specific rendering bugs? @bmorel reported a problem on rush-station here: https://github.com/Unvanquished/Unvanquished/issues/2500

Could you load that map and see if you have any odd issues at the human start base?

**Comment by illwieckz** [comment]
@slipher do you reproduce it with fresh homepath (and then default configuration)?

What is the system and driver version? Is it Windows?

**Comment by slipher** [comment]
> @bmorel reported a problem on rush-station here: [Unvanquished/Unvanquished#2500](https://github.com/Unvanquished/Unvanquished/issues/2500)
> 
> Could you load that map and see if you have any odd issues at the human start base?

Yes I get the #2500 issue



> @slipher do you reproduce it with fresh homepath (and then default configuration)?

Yes

> What is the system and driver version? Is it Windows?

```
Driver Date: 2/28/2018
Driver Version: 23.20.16.4974
```

Yes. Pretty old but I can't find anywhere to update it.

**Comment by bmorel** [comment]
I don't reproduce on "Intel(R) Pentium(R) Gold G5500 CPU @ 3.80GHz"
![2023-11-07](https://github.com/DaemonEngine/Daemon/assets/1316300/c33408d4-3895-4ff0-a9a5-ae8095cc74da)

About the rendering problems I mention in Unvanquished/Unvanquished#2500, the increase of that mess' appearance was drastic between 0.53 and 0.54, so I don't think it is "just an intel bug".
Note that I am *not* using the release daemon anymore, as it's regressions are simply too severe, so I can not name the exact commit my engine is built off.

**Comment by illwieckz** [comment]
I don't reproduce on HD 5500 (i5 5200U, 5th gen, Broadwell), neither on Windows, neither on Linux.

**Comment by illwieckz** [comment]
I don't reproduce on HD 520 (i7 6500U, 6th gen, Skylake), neither on Windows,, neither on Linux.

**Comment by illwieckz** [comment]
@cu-kai reported some weeks ago he didn't reproduced the bug on UHD 620, I guess it was on Linux:

```
2023-11-02 03:06:42 +0100 <cu-kai> tell you what, i'll launch unv on my UHD620
                          and tell you if station15 is broken
2023-11-02 03:09:19 +0100 <cu-kai> no bug on my system
2023-11-02 03:10:03 +0100 <cu-kai> https://p.mort.coffee/LX0.jpg
2023-11-02 03:13:12 +0100 <cu-kai> anyway, on medium, high and ultra settings,
                          this water looks fine on the UHD 620
```

![LX0](https://github.com/DaemonEngine/Daemon/assets/2311649/e7caccad-f022-4bc5-90bc-c19f5e4818d1)

**Comment by illwieckz** [comment]
Chip|Windows|Linux|Tester
--|--|--|--
HD 5500|✅️|✅️|illwieckz
HD 520|✅️|✅️|illwieckz
UHD 620|✅️|❔️|cu-kai
UHD 630|❌️|❔️|slipher

**Comment by cu-kai** [comment]
On Windows 11 23H2 (build 22631.2428), Intel UHD 620, driver 30.0.101.1122 I cannot reproduce this bug.

**Comment by slipher** [comment]
I tested some more and it turns out the confetti can appear with all sorts of particle systems: most human weapons, the alien structure bleed effect... not just the waterfall. So it seems something broke with my system. Maybe a bit flipped in the driver or something.

Anyway I tried looking for the driver update again and found it. I guess I didn't find it last time because the page contains only the name of the CPU models, not the GPU model. With driver version 31.0.101.2115 (11/16/2022) I no longer get the bug.

**Comment by illwieckz** [comment]
I reproduce a very similar bug on AMD Radeon PRO W7600, Linux, radeonsi OpenGL driver.

On my end it happens on the leaves, and is more subtle because the confettis are green like the leaves.

![unvanquished_2024-02-12_204257_000](https://github.com/DaemonEngine/Daemon/assets/2311649/2a2de6a4-47a3-4e74-8691-eb0aa1279364)

![unvanquished_2024-02-12_204312_000](https://github.com/DaemonEngine/Daemon/assets/2311649/def0252a-c0c9-4f0a-94b3-fd33d32b9f14)

**Comment by slipher** [comment]
Doesn't seem especially similar to me. That should get its own thread
